using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class Appriation_LE : MonoBehaviour {


    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 6;
        MusicInfo.name = "Apparition LE-MIX";
        MusicInfo.composer = "Park, Jin-bae";
        MusicInfo.visualizer = "Default";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        //int comboCalc = 0;
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "Normal";
        normal.catchParase = normal_img;
        normal.level = 4;
        MusicInfo.list.Add(normal);

        //comboCalc = 0;
        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Hard";
        hard.level = 5;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        //comboCalc = 0;
        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Extreme";
        extreme.level = 20;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("Normal"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 7.471f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 9.248f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 11.026f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 12.804f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 13.248f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.693f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 14.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 14.582f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 15.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 16.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 16.359f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 17.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 17.915f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 18.137f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 18.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 19.026f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 19.47f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 19.915f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 20.137f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 20.359f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 20.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 20.804f, 21.581f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 21.693f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 22.47f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.804f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23.248f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 23.47f, 23.804f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 24.248f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 24.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 25.026f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 25.248f, 25.581f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 26.026f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 26.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 26.804f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 27.026f, 27.359f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.804f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 28.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 28.581f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 28.804f, 29.137f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 29.581f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 29.915f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30.359f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 30.581f, 30.915f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 31.359f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 31.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 32.359f, 32.692f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 33.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 33.915f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 34.137f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.581f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 35.026f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 35.47f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 35.915f, 36.692f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 36.803f, 37.581f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 37.692f, 39.359f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 37.692f, 39.359f, ";"));
            input.Notes.Add(new Data.NoteInfo(true, 39.47f, 42.914f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 42.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 42.803f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 43.026f, 44.692f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 44.803f, 45.581f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 45.692f, 46.47f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 46.581f, 48.248f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 48.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 48.581f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 48.803f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 49.026f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 49.248f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 49.47f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 49.692f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 49.914f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 50.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 50.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 50.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 50.692f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 50.914f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.137f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 51.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.914f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 52.137f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 52.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 52.47f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 52.692f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 53.025f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 53.47f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 53.692f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.914f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 54.137f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 54.248f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 54.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 55.248f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.47f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 55.692f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 55.914f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 56.025f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 56.248f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 56.581f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 57.025f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 57.248f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 57.47f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 57.692f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 57.803f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.025f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 58.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 58.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.025f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 59.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 59.47f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 59.581f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 59.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 60.136f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 60.581f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 60.803f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 61.025f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 61.248f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 61.359f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 61.914f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 62.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 62.581f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 63.025f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 63.47f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 63.914f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 64.359f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 64.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 64.803f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 65.025f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 65.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 65.47f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 65.692f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 65.914f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 66.136f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.359f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 66.581f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 66.803f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 67.025f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 67.248f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 67.47f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 67.692f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 67.914f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 68.136f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 68.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 68.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 68.803f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 69.025f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.247f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 69.47f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 70.136f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 70.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.025f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.47f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 71.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71.914f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 72.136f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72.359f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 72.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 72.803f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 73.025f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 73.247f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 73.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 73.692f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.914f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74.136f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 74.359f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.581f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 74.803f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 75.025f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 75.247f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.47f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 75.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.914f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 76.136f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.359f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 76.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.803f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 77.247f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 77.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78.136f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78.581f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 78.581f, 0.2f, "a"));

        }
        else if (input.Difficulty.Equals("Hard"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 0.36f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 0.582f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 0.804f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 1.026f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 1.248f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 1.471f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 1.693f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 1.915f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 2.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 2.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 2.582f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 2.804f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 3.026f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 3.248f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 3.471f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 3.693f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 3.915f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 4.137f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 4.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 4.582f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 4.804f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 5.026f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 5.248f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 5.471f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 5.693f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 5.915f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 6.137f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 6.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 6.582f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 6.804f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 7.026f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 7.248f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 7.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 7.471f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 7.471f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 7.471f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 7.915f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 7.915f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 8.137f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 8.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 8.248f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 8.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 8.582f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 8.582f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 9.026f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 9.026f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 9.026f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 9.248f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 9.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 9.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 9.693f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 9.693f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 9.915f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 9.915f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 10.026f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 10.026f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 10.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 10.359f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 10.804f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 10.804f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 11.026f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 11.026f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 11.026f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 11.47f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 11.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 11.804f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 11.804f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 11.915f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 11.915f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 12.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 12.137f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 12.582f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 12.582f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 12.582f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 12.804f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 12.804f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 12.804f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 13.248f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 13.248f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 13.47f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 13.47f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 13.582f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 13.582f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 13.915f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.915f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 14.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 14.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 14.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 14.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 14.582f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 14.582f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 14.582f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 15.026f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 15.026f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 15.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 15.248f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 15.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 15.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 15.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 15.693f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 15.693f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 16.137f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 16.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 16.359f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 16.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 16.359f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 16.804f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 16.804f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 17.026f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 17.026f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 17.137f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 17.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 17.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 17.47f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 17.47f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 17.915f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 17.915f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 17.915f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 18.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 18.137f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 18.137f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 18.581f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 18.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 18.581f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 18.804f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 18.804f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 18.915f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 18.915f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 19.026f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 19.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 19.248f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 19.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 19.693f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 19.693f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 19.915f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 19.915f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 20.137f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 20.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 20.359f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 20.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 20.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 20.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 20.804f, 21.581f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 20.804f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21.026f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21.248f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21.693f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 21.915f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 22.137f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 22.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 22.248f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 22.47f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 22.804f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23.026f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 23.248f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 23.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 23.47f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 23.693f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.804f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 23.915f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 23.915f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.026f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 24.248f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 24.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 24.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 24.804f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 25.026f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 25.026f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 25.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 25.248f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 25.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 25.693f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 25.693f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 25.804f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 26.026f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 26.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 26.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 26.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 26.804f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 27.026f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 27.026f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.137f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.248f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.359f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 27.47f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 27.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.804f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 27.915f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 28.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 28.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 28.581f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 28.804f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 28.804f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 29.026f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.248f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 29.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 29.359f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 29.581f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 29.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 29.915f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 30.359f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 30.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 30.581f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 30.692f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30.804f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 30.915f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 31.026f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 31.026f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 31.359f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 31.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 31.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 31.915f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 32.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 32.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 32.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 32.359f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 32.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 32.804f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 32.804f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 32.915f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 33.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 33.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 33.915f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 34.137f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 34.248f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 34.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.47f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 34.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 34.692f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 34.803f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 34.915f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 35.026f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 35.137f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 35.248f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 35.359f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 35.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 35.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 35.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 35.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 35.915f, 36.692f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 35.915f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.137f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 36.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 36.47f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 36.692f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 36.803f, 37.581f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 36.803f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 37.026f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 37.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 37.47f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 37.692f, 39.359f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 37.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 37.692f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 37.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 37.915f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 38.026f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 38.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 38.137f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 38.248f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 38.47f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 38.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 38.803f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 39.026f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 39.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 39.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 39.47f, 42.914f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 39.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 39.47f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 39.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 39.915f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 39.915f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 40.026f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 40.248f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 40.581f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 40.803f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 41.026f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 41.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 41.248f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 41.359f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 41.47f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 41.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 41.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 41.692f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 41.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 42.026f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 42.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 42.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 42.803f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 42.803f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 43.026f, 44.692f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 43.026f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 43.026f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 43.248f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 43.47f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 43.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 43.581f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 43.803f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 43.914f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 44.137f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 44.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 44.803f, 45.581f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 44.803f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 44.803f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 44.914f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.026f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 45.137f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 45.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 45.581f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 45.692f, 46.47f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 45.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 45.914f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 46.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 46.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 46.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 46.581f, 48.248f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 46.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 46.581f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 46.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 47.026f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.026f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 47.137f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 47.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 47.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 47.914f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 48.137f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 48.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 48.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 48.47f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 48.581f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 48.692f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 48.803f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 48.914f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 49.026f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 49.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 49.248f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 49.359f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 49.47f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 49.581f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 49.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 49.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49.914f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 50.026f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 50.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 50.359f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 50.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 50.692f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 50.914f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.137f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 51.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.914f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 52.137f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 52.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 52.47f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 52.692f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 53.025f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 53.47f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 53.692f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.914f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 54.137f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 54.248f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 54.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 55.248f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.47f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 55.692f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 55.914f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 56.025f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 56.248f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 56.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 57.025f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 57.248f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 57.47f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 57.692f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 57.803f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.025f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 58.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 58.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.025f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 59.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 59.47f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 59.581f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 59.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 60.136f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 60.581f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 60.803f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 61.025f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 61.248f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 61.359f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 61.914f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 62.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 62.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 62.581f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 62.692f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 62.803f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 62.914f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 63.025f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 63.025f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 63.136f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 63.248f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 63.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 63.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 63.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 63.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 63.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 63.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 63.914f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 63.914f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 64.025f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 64.136f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 64.248f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 64.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 64.359f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 64.581f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 64.803f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 64.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 64.914f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 65.136f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 65.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 65.359f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 65.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 65.803f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 66.136f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 66.136f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 66.359f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 66.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 66.581f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 66.692f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.914f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 67.025f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 67.248f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 67.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 67.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 67.692f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 67.914f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 67.914f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 68.136f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 68.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 68.359f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 68.47f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 68.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 68.803f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 69.025f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.247f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 69.47f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 69.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 69.692f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.914f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 70.136f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 70.136f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 70.247f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.47f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 70.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 70.803f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71.025f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.247f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.247f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 71.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71.692f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 71.914f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.914f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 72.025f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 72.247f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 72.47f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 72.803f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 72.914f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 73.247f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 73.247f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 73.247f, 76.692f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 73.47f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 73.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 73.692f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 73.803f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.025f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.136f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 74.359f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 74.803f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 74.803f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 75.025f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 75.025f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 75.247f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 75.47f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 75.47f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 75.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 75.803f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.914f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76.136f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.359f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76.581f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 76.803f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76.803f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 76.914f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 77.025f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 77.136f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 77.247f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 77.247f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 77.358f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.47f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 77.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 77.692f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 77.803f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 77.914f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.025f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 78.136f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78.136f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 78.247f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 78.358f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 78.47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 78.581f, 0.2f,"q"));
            input.Notes.Add(new Data.NoteInfo(false, 78.581f, 0.2f, "p"));

        }
        else if (input.Difficulty.Equals("Extreme"))
        {
            input.Notes.Add(new Data.NoteInfo(true, 0.0f + 0.00f, 1.09f, "j"));
        }
    }
}
