using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class Flicker : MonoBehaviour {

    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 28;
        MusicInfo.name = "Flicker";
        MusicInfo.composer = "Chelp";
        MusicInfo.visualizer = "Haru-Sabin & FOX-B";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "Normal";
        normal.catchParase = normal_img;
        normal.level = 6;
        MusicInfo.list.Add(normal);

        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Hard";
        hard.level = 12;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Extreme";
        extreme.level = 3;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("Normal"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.021f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 0.566f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 1.657f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 3.293f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 3.839f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 4.93f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 6.566f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 7.111f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 8.202f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 9.839f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 16.657f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 17.202f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 17.748f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 18.293f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 18.839f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 19.384f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 19.93f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 20.475f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 21.02f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 21.566f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.111f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.657f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 23.202f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 23.748f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.293f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.566f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 24.839f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.975f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 25.657f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.748f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 27.839f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 28.93f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.02f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 31.111f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 31.657f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 32.066f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.475f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 32.884f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 33.293f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 34.111f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.657f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 35.202f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 35.748f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.293f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 36.839f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 37.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 37.657f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 38.475f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 39.02f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 39.566f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.111f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.657f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 41.202f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 41.748f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.293f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.566f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.111f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 43.657f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 44.202f, 0.2f,"l"));
            input.Notes.Add(new Data.NoteInfo(false, 44.748f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.293f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.839f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 46.384f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 46.93f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.339f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.611f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.884f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 48.43f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 49.111f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 49.657f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 50.066f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 50.339f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 50.611f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 50.748f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.293f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 52.111f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 52.93f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 53.475f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.884f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 54.293f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 54.566f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 54.839f, 55.248f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 55.657f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 56.475f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 57.02f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 57.43f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 57.839f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 58.111f, 59.748f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 60.02f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 60.839f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 61.657f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 62.202f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 62.611f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 63.02f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 63.293f, 63.702f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 64.384f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.566f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 67.111f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 67.657f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 68.202f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 68.748f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 69.293f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 69.839f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 70.384f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 70.93f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 71.475f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 72.02f, 72.43f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 73.111f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 73.657f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.202f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.748f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 75.293f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 75.702f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76.793f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 77.475f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78.02f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 78.566f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 79.111f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 79.657f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 80.202f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 80.748f, 81.157f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 81.839f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.384f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82.93f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.475f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 84.02f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 84.43f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84.839f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 85.248f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.657f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 86.202f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 86.748f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.293f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 87.839f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 88.384f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 88.93f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 89.475f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 89.748f, 90.157f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 90.566f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 91.111f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 91.657f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 92.202f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 92.748f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 93.293f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 93.839f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 94.384f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 94.93f, 95.748f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 96.02f, 96.839f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 97.111f, 97.93f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 98.066f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.293f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.702f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.975f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.248f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.793f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 101.475f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 102.02f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 102.02f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 102.43f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 102.702f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 102.975f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 103.111f, 0.2f, "j"));

        }
        else if (input.Difficulty.Equals("Hard"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 0.536f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 1.627f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 1.627f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 2.172f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 2.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 2.445f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 2.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 2.718f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 3.263f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 3.809f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 4.9f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 5.172f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 5.445f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 5.718f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 5.99f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 6.536f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 7.081f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 8.172f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 8.172f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 9.627f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 9.718f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 9.809f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 9.809f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 11.172f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 11.718f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 12.263f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 12.809f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 13.354f, 14.581f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 16.354f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 16.763f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 17.036f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 17.172f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 17.309f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 17.581f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 17.99f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 18.536f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 18.672f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 18.945f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 19.218f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 19.354f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 19.49f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 20.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 20.445f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 20.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 20.718f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 20.854f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 21.127f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 21.672f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 21.945f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.081f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 22.218f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.354f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 22.49f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 22.627f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 22.763f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 22.9f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.036f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.309f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 23.581f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 23.854f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 24.4f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.536f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 24.809f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.809f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.945f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 24.945f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 25.081f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 25.081f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 25.354f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 25.627f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 25.627f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 25.763f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 26.036f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 26.172f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 26.309f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 26.718f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 26.718f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.263f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.263f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 27.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.536f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.672f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.945f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 28.218f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 28.354f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 28.627f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 28.763f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 28.9f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 28.9f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 29.036f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 29.172f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 29.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 29.445f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 29.445f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 29.445f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.581f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 29.718f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 29.854f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 29.99f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 30.127f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 30.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30.672f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30.809f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 31.081f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 31.218f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 31.354f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 31.49f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 31.627f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 31.627f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 31.9f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 32.036f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 32.036f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.309f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 32.445f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 32.445f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 32.718f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 32.854f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.854f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.127f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 33.263f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 33.263f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33.536f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 33.809f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 33.809f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.081f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 34.218f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 34.218f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 34.354f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.49f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 34.627f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 34.763f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.763f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 35.036f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 35.036f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 35.445f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 35.445f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 35.99f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 35.99f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 36.127f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.4f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 36.4f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.672f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 36.809f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 36.945f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 37.081f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 37.354f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 37.49f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 37.763f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 37.9f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.036f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 38.172f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 38.172f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 38.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 38.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 38.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.718f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 38.854f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 38.854f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 39.127f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 39.127f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 39.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 39.536f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 39.672f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 39.672f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 39.809f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 39.945f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 39.945f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 40.081f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 40.218f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 40.218f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.354f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 40.49f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 40.763f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 40.763f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 41.036f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 41.036f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 41.309f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 41.309f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 41.445f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 41.718f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 41.854f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 41.854f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 42.263f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.263f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 42.4f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 42.536f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 42.536f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 42.809f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 42.809f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 43.081f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 43.081f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.218f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 43.218f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 43.49f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 43.49f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 43.763f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 43.763f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.036f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 44.172f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 44.172f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 44.445f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.581f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 44.718f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.718f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.854f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.99f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 44.99f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 45.127f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 45.127f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.4f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 45.4f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 45.672f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 45.672f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 46.081f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 46.172f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 46.263f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 46.354f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 46.536f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 46.627f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 46.809f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 46.9f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 46.9f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 46.9f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 46.9f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.036f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 47.172f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 47.309f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 47.309f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 47.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.581f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 47.581f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 47.854f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.854f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 47.854f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 48.127f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 48.263f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 48.4f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 48.4f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 48.4f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 48.672f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 48.809f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 48.945f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 49.081f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 49.081f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 49.081f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 49.354f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49.422f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 49.49f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49.559f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 49.627f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 49.627f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 49.763f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 50.036f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 50.036f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 50.036f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 50.036f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 50.309f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 50.309f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 50.309f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 50.309f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 50.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 50.718f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 50.718f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 50.718f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 50.99f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 51.127f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.263f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 51.263f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 51.4f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 51.672f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 51.809f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 52.081f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 52.081f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 52.218f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 52.49f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 52.627f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 52.9f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 52.9f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 53.036f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.309f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.445f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 53.445f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 53.581f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 53.854f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 53.854f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.99f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.127f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 54.263f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 54.263f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 54.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 54.536f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 54.672f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.809f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 54.877f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 54.945f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.013f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 55.081f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.15f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 55.218f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 55.354f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 55.627f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 55.627f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 55.763f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 56.036f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 56.172f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 56.445f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 56.445f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 56.581f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 56.854f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 56.99f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 56.99f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 57.127f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 57.4f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 57.536f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 57.536f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 57.672f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 57.809f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.081f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 58.081f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 58.172f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 58.263f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 58.354f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 58.627f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 58.627f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 58.695f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 58.809f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 58.9f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 58.9f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.081f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 59.172f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 59.354f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.445f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 59.445f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 59.718f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 59.718f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 59.718f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.854f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 59.99f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 59.99f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 60.127f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 60.4f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 60.536f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 60.536f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 60.809f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 60.809f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 60.945f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.218f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.354f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 61.354f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 61.627f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 61.627f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.763f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 62.036f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 62.172f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 62.172f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 62.172f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 62.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 62.581f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 62.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 62.581f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 62.718f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 62.99f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 62.99f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 62.99f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 63.127f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 63.263f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 63.263f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 63.4f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 63.536f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 63.672f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 63.809f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 64.081f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 64.218f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 64.354f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 64.49f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 64.763f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 65.036f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 65.172f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 65.309f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 65.445f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 65.445f, 66.4f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 65.581f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 65.718f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 65.854f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 65.99f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 66.127f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.263f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 66.4f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.536f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 66.536f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 66.672f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 66.809f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 66.945f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 67.081f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 67.081f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 67.218f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 67.354f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 67.49f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 67.627f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 67.627f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 67.763f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 67.9f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 68.036f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 68.172f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 68.309f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 68.445f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 68.581f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 68.718f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 68.718f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 68.718f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 68.854f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 69.127f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 69.263f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 69.263f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 69.809f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 69.945f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 70.081f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 70.218f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.354f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 70.354f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 70.354f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 70.49f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.627f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 70.763f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 70.9f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 70.9f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.036f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 71.172f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 71.309f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 71.445f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 71.445f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.445f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 71.718f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 71.854f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71.99f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.99f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 72.263f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 72.4f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 72.536f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 72.536f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 72.672f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 72.809f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72.945f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.081f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 73.081f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 73.218f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.354f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 73.49f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 73.627f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 73.627f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 73.627f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 73.763f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.9f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74.036f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 74.172f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 74.172f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 74.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.309f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74.445f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 74.581f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.581f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 74.718f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.718f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 74.854f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74.99f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 75.127f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.263f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 75.263f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 75.4f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 75.536f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 75.536f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.672f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 75.672f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 75.809f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 75.945f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 75.945f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.218f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76.218f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 76.354f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 76.49f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 76.49f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.763f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76.763f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 77.036f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 77.172f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 77.172f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.309f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 77.445f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 77.445f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 77.445f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 77.581f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 77.854f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 77.99f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 77.99f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78.263f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 78.4f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.536f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 78.536f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78.672f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 78.945f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 79.081f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 79.081f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 79.354f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 79.49f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 79.627f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 79.627f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 79.763f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 79.9f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 80.036f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80.172f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 80.172f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 80.172f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 80.309f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 80.445f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 80.581f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 80.581f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 80.99f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81.4f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 81.536f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81.536f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 81.672f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 81.809f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81.809f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 81.945f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 82.081f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 82.218f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.354f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82.354f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 82.49f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 82.627f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82.763f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 82.763f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.9f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 82.9f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.036f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 83.172f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 83.172f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.309f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 83.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.445f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 83.581f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 83.718f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 83.718f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.854f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 83.99f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 83.99f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 83.99f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 84.127f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 84.263f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84.4f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 84.4f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 84.4f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 84.536f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 84.672f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 84.809f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 84.809f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 84.809f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 84.945f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 85.081f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 85.218f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 85.218f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 85.218f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.354f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 85.49f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 85.627f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 85.627f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 85.627f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 85.763f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.9f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 86.036f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 86.172f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 86.172f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 86.309f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 86.581f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 86.718f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 87.536f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 87.672f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 87.809f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.809f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 87.945f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 88.081f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 88.218f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 88.354f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 88.49f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 88.627f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 88.763f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 88.9f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 88.9f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 89.036f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 89.172f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 89.309f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 89.445f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 89.445f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 89.581f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 89.718f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 89.718f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 89.854f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 89.854f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 89.99f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 89.99f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 90.127f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 90.4f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 90.536f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 90.672f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 90.945f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 91.081f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 91.354f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 91.627f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 91.9f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 91.9f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 92.036f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 92.172f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 92.172f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92.309f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 92.445f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 92.581f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 92.718f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 92.854f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 92.99f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 93.127f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 93.263f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 93.263f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 93.4f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93.536f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 93.672f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 93.672f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93.945f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 94.081f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 94.218f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.218f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 94.49f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 94.627f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.627f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 94.763f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 94.9f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 94.9f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 95.036f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 95.172f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 95.309f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 95.445f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 95.445f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 95.581f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 95.718f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 95.854f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 95.99f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 96.127f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96.127f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 96.263f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 96.4f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96.4f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 96.536f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 96.672f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 96.809f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96.809f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 96.945f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 97.081f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 97.081f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 97.218f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 97.354f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 97.49f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 97.627f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 97.627f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 97.9f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 98.036f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 98.036f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 98.036f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 98.309f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 98.718f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 98.99f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 99.127f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 99.263f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.263f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 99.263f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 99.4f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 99.536f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 99.672f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.672f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 99.672f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 99.945f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.945f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 99.945f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 100.218f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 100.218f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 100.218f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.49f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 100.627f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 100.763f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.763f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 100.763f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 101.036f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 101.172f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 101.172f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 101.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101.445f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 101.445f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 101.445f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 101.718f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 101.786f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101.854f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 101.922f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101.99f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 101.99f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 101.99f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 102.127f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 102.4f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 102.4f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 102.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 102.672f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 102.672f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 102.672f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 102.945f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 102.945f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 103.081f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 103.081f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 103.081f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 103.081f, 0.2f, "d"));

        }
        else if (input.Difficulty.Equals("Extreme"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
    }
}
