using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class Fly_Away : MonoBehaviour {

    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 24;
        MusicInfo.name = "Fly Away";
        MusicInfo.composer = "XeoN";
        MusicInfo.visualizer = "SB_ENGINEER";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "Normal";
        normal.catchParase = normal_img;
        normal.level = 6;
        MusicInfo.list.Add(normal);

        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Hard";
        hard.level = 12;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Extreme";
        extreme.level = 3;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("Normal"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 0.428f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 0.642f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 1.071f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 1.285f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 1.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 1.714f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 2.142f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 2.357f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 2.785f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 3.214f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 3.428f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 3.642f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 3.857f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 4.071f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 4.5f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 4.714f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 4.928f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 5.142f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 5.357f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 5.571f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 5.785f, 6.75f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 6.857f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 7.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 7.714f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 8.142f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 8.357f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 8.571f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 9.857f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 10.071f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 10.285f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 10.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 10.714f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 10.928f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 11.142f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 11.571f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 11.785f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 12f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 12.214f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 12.428f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 12.642f, 13.607f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.714f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 14.142f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 14.357f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 14.571f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 14.785f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 15f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 15.214f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 15.857f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 16.285f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 16.714f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 17.142f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 18f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 18.214f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 18.642f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 19.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 19.714f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 20.142f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 20.571f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 21.428f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 21.642f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21.857f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.071f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.928f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 23.357f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.571f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 24f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.857f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 25.285f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 25.714f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 26.357f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 27f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 27.428f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.535f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 27.642f, 29.035f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 29.142f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.357f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 29.571f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.785f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.857f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 31.071f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 31.285f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 31.5f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 32.571f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 32.785f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.214f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 34.285f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 34.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 34.714f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 34.928f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.214f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 36.428f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.642f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 37.285f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 37.285f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 37.714f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 37.928f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 38.142f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.357f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 39f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 39f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 39.428f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 39.642f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 39.857f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 40.071f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.714f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 40.714f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 41.142f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 41.357f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 41.571f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 41.785f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 42.857f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 42.857f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 43.5f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 44.142f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.357f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 44.571f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 45f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 45.214f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 45.642f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 45.857f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 46.071f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 46.285f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 47.357f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 47.571f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 47.785f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 48.428f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 48.642f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 49.071f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 49.285f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49.5f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 49.714f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 50.357f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 51f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.214f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 51.428f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 52.071f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 53.142f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 54.214f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 54.428f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 54.642f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 55.285f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 56.357f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 56.571f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 57f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 57.214f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 57.857f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.071f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 58.285f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 59.357f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 59.571f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 59.785f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 60.857f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.071f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 61.285f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 61.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 62.357f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 62.571f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 63f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 63.428f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 64.071f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 64.714f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 65.142f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 65.785f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 66.857f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 67.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 68.142f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 68.571f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 68.571f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 69.214f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.857f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.285f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.5f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 70.714f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.928f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71.142f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 71.357f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 71.571f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 71.785f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 72f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72.214f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 72.428f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72.642f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 72.857f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 73.071f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 73.285f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 73.5f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 73.714f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 73.928f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74.142f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.357f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74.571f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 74.785f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 75.214f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 75.428f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 75.642f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.857f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 76.071f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 76.285f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 76.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.714f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 76.928f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 77.142f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 77.357f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.571f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 77.785f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 78f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 78.214f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.428f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 78.642f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.857f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 79.071f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 79.285f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 79.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 79.714f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 79.928f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 80.142f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 80.357f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80.571f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 80.785f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 81f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 81.214f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 81.428f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 81.642f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 81.857f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 82.071f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 82.285f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 82.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82.714f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.928f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 83.142f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.357f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 83.571f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.785f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 84f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 84f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 84.428f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.071f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 86.142f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 86.571f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 86.892f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.214f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.857f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 88.5f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 88.928f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 89.571f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 90f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 90.321f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 90.642f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 90.857f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 91.285f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 91.928f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 92.357f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 93.428f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 93.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 94.071f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 94.714f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 95.357f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 95.785f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 96.321f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 96.642f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 96.964f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 97.178f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 97.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 97.714f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 98.035f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 98.357f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 98.678f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 99f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 99.214f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 99.428f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.428f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 100.071f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 100.714f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 100.928f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 101.142f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 101.571f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 101.785f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 102.214f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 102.428f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 102.642f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 102.857f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 103.928f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 104.142f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 104.357f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 105f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 105.214f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 105.642f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 105.857f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 106.071f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 106.285f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 106.928f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 107.571f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 107.785f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 108f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 108.642f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 109.714f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 110.785f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 111f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 111.214f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 111.857f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 112.071f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 112.928f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 113.142f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 113.571f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 113.785f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 114.428f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 114.642f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 114.857f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 115.928f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 116.142f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 116.357f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 117.428f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117.642f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 117.857f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 118.071f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 118.928f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 119.142f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 119.571f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 120f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 120.642f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 121.285f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 121.714f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 122.357f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 123.428f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 124.071f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 124.714f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 125.142f, 0.2f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 125.142f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 125.785f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 126.428f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 126.857f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 126.857f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 127.071f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 127.285f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 127.5f, 0.2f, "j"));

        }
        else if (input.Difficulty.Equals("Hard"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
        else if (input.Difficulty.Equals("Extreme"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
    }
}
