using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class How_To_Enjoy : MonoBehaviour {

    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 16;
        MusicInfo.name = "How to Enjoy";
        MusicInfo.composer = "Lunatic Sound";
        MusicInfo.visualizer = "";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "Normal";
        normal.catchParase = normal_img;
        normal.level = 6;
        MusicInfo.list.Add(normal);

        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Hard";
        hard.level = 12;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Extreme";
        extreme.level = 3;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("Normal"))
        {
            input.Notes.Add(new Data.NoteInfo(true, 0.36f, 0.84f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 0.84f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 1.8f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 2.76f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 3.72f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 4.68f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 5.64f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 6.6f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 6.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 7.2f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 7.44f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 8.04f, 8.4f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 8.52f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 8.76f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 8.88f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 9f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 9.36f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 9.6f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 9.72f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 9.84f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 9.96f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 10.08f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 10.2f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 10.44f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 10.56f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 10.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 10.92f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 11.04f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 11.28f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 11.52f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 11.64f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 11.76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 11.88f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 12f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 12.12f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 12.36f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 12.6f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 12.84f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 12.96f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.2f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 13.44f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 13.56f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 13.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 13.8f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 13.92f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 14.04f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 14.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 14.52f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 14.76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 14.88f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 15.12f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 15.36f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 15.72f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 15.84f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 15.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 16.08f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 16.2f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 17.16f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 18.12f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 19.08f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 21.48f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21.72f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 21.96f, 23.88f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 23.4f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 23.64f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 23.88f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 24.12f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 24.36f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 24.48f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 24.72f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 24.96f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 25.08f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 25.2f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 25.32f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 25.44f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 25.56f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 25.8f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 26.04f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 26.28f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 26.64f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 26.88f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 27f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.12f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 27.24f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.36f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 27.48f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.72f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.96f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 28.2f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.32f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 28.56f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 28.8f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 28.92f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 29.04f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.16f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 29.28f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 29.64f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 29.76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30.12f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.36f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.6f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 30.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 31.08f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 31.2f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 31.32f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 31.44f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 31.56f, 32.52f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 32.52f, 33.24f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 33.24f, 34.68f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 36.36f, 36.72f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 36.84f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 37.08f, 38.76f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 38.76f, 39.24f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 39.24f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 39.48f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 39.72f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 39.84f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.08f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.32f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 40.44f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.56f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 40.68f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 40.8f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 40.92f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 41.16f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 41.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 41.64f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 41.76f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 42f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 42.24f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 42.36f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 42.48f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.6f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 42.72f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.84f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 43.08f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.32f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 43.56f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.68f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 43.92f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.16f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.28f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.4f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 44.52f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.64f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 44.76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 45f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 45.24f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.48f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 45.6f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.84f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 46.08f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 46.2f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 46.32f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 46.44f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 46.56f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 46.68f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 46.92f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 48f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 48.24f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 48.84f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 50.76f, 53.64f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 53.64f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 53.76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.88f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.12f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 54.36f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 54.6f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 54.84f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 55.08f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 55.2f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.44f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.68f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 55.8f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 55.92f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 56.04f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 56.16f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 56.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 56.52f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 56.76f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 57f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 57.12f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 57.36f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 57.6f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 57.72f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 57.84f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 57.96f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 58.08f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 58.2f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 58.44f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.68f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 58.92f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 59.04f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 59.52f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 59.64f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 59.76f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.88f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 60f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 60.12f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 60.36f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 60.6f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 60.84f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 60.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.2f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 61.44f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 61.56f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 61.8f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 61.92f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 62.04f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 62.28f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 62.28f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 63.24f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 63.24f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 64.2f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 64.2f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 65.16f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 65.16f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.12f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 66.12f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 67.8f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 69.24f, 69.48f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 69.96f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 70.2f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.44f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 70.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 70.8f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.92f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 71.04f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 71.16f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 71.28f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 71.64f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 71.76f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71.88f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 72.12f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 72.36f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 72.6f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 72.84f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 72.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 73.2f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 73.8f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 73.8f, 77.52f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 74.04f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.28f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 74.52f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.64f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.76f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74.88f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.12f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 75.24f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.36f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 75.72f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 75.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.2f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 76.44f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.56f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 76.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 76.92f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.16f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 77.88f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 78.12f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 78.36f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 78.48f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 78.6f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 78.84f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 79.08f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 79.32f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 79.56f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 79.8f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 79.92f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 80.04f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 80.28f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 80.52f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80.76f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 81f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 81.24f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 81.48f, 85.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 81.6f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 81.72f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 81.84f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 81.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 82.08f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 82.2f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 82.32f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 82.56f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82.68f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.8f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82.92f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.04f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 83.16f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.4f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 83.52f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.64f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 83.76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.88f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 84f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84.12f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 84.24f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84.36f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 84.48f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 84.6f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 84.72f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 84.84f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 84.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.08f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 85.32f, 86.28f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 86.52f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 87.24f, 87.96f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 88.08f, 88.32f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 88.44f, 89.04f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 89.16f, 90.24f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 90.36f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 90.84f, 91.56f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 92.04f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 92.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 92.4f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 92.52f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 92.64f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 93f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 93.24f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 93.48f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 93.72f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 93.96f, 0.2f,"a"));
            input.Notes.Add(new Data.NoteInfo(false, 94.2f, 0.2f,"q"));
            input.Notes.Add(new Data.NoteInfo(false, 94.44f, 0.2f,"a"));
            input.Notes.Add(new Data.NoteInfo(false, 94.68f, 0.2f,"q"));
            input.Notes.Add(new Data.NoteInfo(false, 94.92f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.92f, 0.2f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 95.4f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 95.4f, 0.2f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 95.64f, 0.2f,"a"));
            input.Notes.Add(new Data.NoteInfo(false, 95.76f, 0.2f,"q"));
            input.Notes.Add(new Data.NoteInfo(false, 96.84f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 96.84f, 10.056f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 97.8f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 98.28f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 98.76f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.68f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 100.92f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101.16f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 101.28f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101.52f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101.76f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 101.88f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 102f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 102.12f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 102.24f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 102.36f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 102.6f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 102.84f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 103.08f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 103.2f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 103.44f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 103.68f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 103.8f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 103.92f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 104.04f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 104.16f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 104.28f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 104.52f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 104.76f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 105f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 105.12f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 105.36f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 105.6f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 105.72f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 105.84f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 105.96f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 106.08f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 106.2f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 106.44f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 106.44f, 106.68f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 106.68f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 106.92f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 106.92f, 107.16f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 107.04f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 107.28f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 107.4f, 107.64f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 107.52f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 107.64f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 107.76f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 107.88f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 107.88f, 108.12f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 108f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 108.12f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 108.24f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 108.36f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 108.6f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 108.84f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 108.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 109.2f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 109.44f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 109.56f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 109.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 109.8f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 109.92f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 110.04f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 110.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 110.52f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 110.76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 110.88f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 111.12f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 111.36f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 111.48f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 111.6f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 111.72f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 111.84f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 111.96f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 112.2f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 112.44f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 112.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 112.8f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 113.04f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 113.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 113.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 113.52f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 113.64f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 113.76f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 113.88f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 114.24f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 114.36f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 114.6f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 114.72f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 114.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 115.2f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 115.32f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 115.44f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 115.56f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 115.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 115.8f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 116.04f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 116.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 116.52f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 116.76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 117f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 117.24f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 117.36f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 117.72f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 117.72f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117.96f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 118.2f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 118.44f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 118.92f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 118.92f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 119.16f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 119.28f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 119.64f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 119.64f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 119.88f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 120.12f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 120.36f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 120.84f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 120.84f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 121.08f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 121.2f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 121.56f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 121.56f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 121.8f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 122.04f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 122.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 122.76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 122.76f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 123f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 123.12f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 123.48f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 123.48f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 123.72f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 123.96f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 124.2f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 124.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 124.68f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 124.92f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 125.04f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 125.4f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 125.4f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 125.64f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 125.88f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 126.12f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 126.6f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 126.6f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 126.84f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 126.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 127.32f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 127.32f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 127.56f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 127.8f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 128.04f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 128.52f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 128.52f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 128.76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 128.88f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 129.24f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 129.24f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 129.72f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 130.92f, 0.2f,"a"));
            input.Notes.Add(new Data.NoteInfo(false, 130.92f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 131.16f, 0.2f,"q"));
            input.Notes.Add(new Data.NoteInfo(false, 131.16f, 0.2f, "space"));


        }
        else if (input.Difficulty.Equals("Hard"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 2.0f, "s"));
        }
        else if (input.Difficulty.Equals("Extreme"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 2.0f, "s"));
        }
    }
}
