using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class MxMxM_Star : MonoBehaviour {

    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 29;
        MusicInfo.name = "MxMxM Star";
        MusicInfo.composer = "TJ.hangneil";
        MusicInfo.visualizer = "Crolul";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "Normal";
        normal.catchParase = normal_img;
        normal.level = 6;
        MusicInfo.list.Add(normal);

        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Hard";
        hard.level = 12;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Extreme";
        extreme.level = 3;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("Normal"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 1.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 2f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 2.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 3.25f, 3.625f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 3.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 4f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 4.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 4.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 5.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 6f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 6.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 7.25f, 7.625f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 7.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 8f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 8.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 8.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 9.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 9.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 10f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 10f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 10.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 10.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 11f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 11.25f, 11.625f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 11.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 11.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 12f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 12f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 12.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 12.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 12.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 13f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 13.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 14f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 14f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 14.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 14.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 15f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 15.25f, 15.625f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 15.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 15.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 16f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 16f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 16.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 16.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 16.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 16.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 17f, 17.5f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 17f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 17.25f, 18.625f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 17.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 18f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 18.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 19f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 19f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 19.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 19.75f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 20f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 20f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 20.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 21.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 21.375f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 21.5f, 21.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 22f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 22f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 22.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 22.5f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 23f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 23.25f, 23.625f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 23.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 24f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 24f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 24.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 24.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 25f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 25f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 25.25f, 26.5f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 26f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 26.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 27f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 27.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 27.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 28f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 28.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 29f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 29.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.375f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 29.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 30f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 30.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 30.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 30.75f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 31f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 31f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 31.25f, 33.125f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 31.25f, 33.25f, ";"));
            input.Notes.Add(new Data.NoteInfo(true, 31.25f, 33.125f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 33.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 34.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 35f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 35.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 35.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 37.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 37.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 38.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 39f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 39.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 39.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 40.5f, 40.875f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 40.5f, 40.875f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 41f, 41.375f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 41f, 41.375f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 41.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 41.5f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 42.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 43.25f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 43.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 45.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 46.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 47.25f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 47.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 48.5f, 48.875f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 48.5f, 48.875f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 48.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 49f, 49.375f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 49f, 49.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 49.5f, 51f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 50f, 50.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 50.5f, 50.875f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 51f, 51.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 51.25f, 53f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 52f, 52.375f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 52.5f, 52.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 53f, 53.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 53.5f, 55f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 54f, 54.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 54.5f, 54.875f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 55f, 55.375f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 55.25f, 56.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 55.5f, 55.875f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 56f, 56.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 56.5f, 56.875f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 56.5f, 56.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 57f, 57.375f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 57f, 57.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 57.5f, 59f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 58f, 58.375f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 58.5f, 58.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 59f, 59.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 59.25f, 61f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 60f, 60.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 60.5f, 60.875f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 61f, 61.375f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 61.5f, 63f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 62f, 62.375f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 62.5f, 62.875f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 63f, 63.375f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 63.25f, 64.375f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 63.5f, 63.875f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 64f, 64.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 64.5f, 64.875f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 64.5f, 64.875f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 65f, 65.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 65f, 65.375f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 65.25f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 65.5f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 65.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 66f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 66f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 66.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 66.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 67f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 67f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 67.25f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 67.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 67.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 68f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 68.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 68.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 68.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 69f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 69f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 69.25f, 71.375f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 70.5f, 70.875f, "p"));
            input.Notes.Add(new Data.NoteInfo(true, 71f, 71.375f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 71.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 71.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 72f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 72.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 72.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 73f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 73.25f, 73.625f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 73.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 73.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 74f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 74.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 74.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 75f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 75.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 75.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 76f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 76.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 77f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 77f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 77.25f, 77.625f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 77.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 78f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 78.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 78.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78.75f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 79f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 79f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 79f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 79.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 79.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 79.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 80f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 80f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 80.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 80.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 81f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 81.25f, 81.625f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 81.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 82f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 82.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 82.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 82.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 83f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 83.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 84f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 84f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 84.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 84.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 85f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 85f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 85.25f, 85.625f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 85.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 85.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 86f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 86f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 86f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 86.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 86.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 86.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 86.75f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 87f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 87f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 87.25f, 88.625f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 88f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 88f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 88.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 88.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 89f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 89f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 89f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 89.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 89.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 89.75f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 90f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 90f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 90f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 90.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 90.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 91f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 91f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 91.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 91.375f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 91.5f, 91.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 91.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 92f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 92f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 92f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 92.5f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 92.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 92.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 93f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 93f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 93.25f, 93.625f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 93.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 93.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 94f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 94f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 94f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 94.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 94.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 94.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 95f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 95f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 95f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 95.25f, 96.5f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 95.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 96f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 96f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 96.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 97f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 97f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 97f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 97.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 97.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 97.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 98f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 98f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 98f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 98.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 98.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 99f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 99f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 99.375f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 99.5f, 99.875f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 99.5f, 99.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 100f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 100.25f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 100.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 100.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 101f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 101.25f, 103.375f, "p"));
            input.Notes.Add(new Data.NoteInfo(true, 101.25f, 103.375f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 101.25f, 103.375f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 103.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 103.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 104f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 104f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 104.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 104.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 105f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 105.25f, 105.625f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 105.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 105.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 106f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 106f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 106.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 106.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 106.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 107f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 107.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 107.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 108f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 108f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 108.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 108.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 109f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 109.25f, 109.625f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 109.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 109.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 110f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 110f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 110.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 110.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 110.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 111f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 111.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 111.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 112f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 112f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 112.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 112.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 113f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 113.25f, 113.625f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 113.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 113.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 114f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 114f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 114.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 114.5f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 114.75f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 115f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 115.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 115.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 116f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 116f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 116.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 116.75f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 117f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 117.25f, 117.625f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 117.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 117.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 118f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 118f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 118.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 118.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 118.5f, 119.375f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 118.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 119f, 119.375f, "p"));

        }
        else if (input.Difficulty.Equals("Hard"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 1.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 2f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 2.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 3.25f, 3.625f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 3.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 4f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 4.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 4.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 5.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 6f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 6.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 7.25f, 7.625f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 7.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 8f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 8.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 8.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 9.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 9.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 10f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 10f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 10.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 10.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 11f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 11.25f, 11.625f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 11.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 11.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 12f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 12f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 12.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 12.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 12.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 13f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 13.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 14f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 14f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 14.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 14.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 15f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 15.25f, 15.625f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 15.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 15.5f, 17.25f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 15.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 16f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 16f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 16.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 16.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 16.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 16.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 17f, 17.5f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 17f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 17.25f, 18.625f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 17.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 17.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 18f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 18.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 18.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 18.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 18.75f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 19f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 19.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 19.25f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 19.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 19.75f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 19.75f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 20f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 20f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 20.25f, 21.125f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 20.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 20.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 20.75f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 20.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 21f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 21.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 21.25f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 21.375f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 21.5f, 21.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 21.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 21.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 22f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 22f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 22.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 22.5f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 22.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 22.75f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 22.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 23f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 23.25f, 23.625f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 23.25f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 23.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 23.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23.75f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 24f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 24f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 24.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 24.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 24.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 24.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.75f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 24.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 25f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 25f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 25.25f, 26.5f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 25.25f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 25.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 25.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 26f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 26.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 26.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 26.75f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 26.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 27f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 27.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 27.25f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 27.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 27.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 27.75f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 28f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 28f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 28.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 28.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 28.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 28.75f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 28.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 29f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 29.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.25f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 29.375f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 29.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 29.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 30f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 30.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 30.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 30.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 30.75f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 30.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 31f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 31f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 31f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 31.25f, 33.125f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 31.25f, 33.25f, "p"));
            input.Notes.Add(new Data.NoteInfo(true, 31.25f, 31.625f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 31.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 32.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 32.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 33.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 34.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 35f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 35.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 35.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 35.25f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 37.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 37.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 37.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 38.5f, 40.125f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 38.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 39f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 39.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 39.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 39.25f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 40.5f, 40.875f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 40.5f, 40.875f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 41f, 41.375f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 41f, 41.375f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 41f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 41.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 41.5f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 41.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 41.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 42f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 42.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 42.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 43f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 43.125f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 43.25f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 43.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.25f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 43.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 43.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 43.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 44f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 44.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 44.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 44.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 45f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 45.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 45.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 45.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 46f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 46.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 46.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 46.875f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 47f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 47f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 47.25f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 47.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 47.25f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 48f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 48.5f, 48.875f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 48.5f, 48.875f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 48.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 48.5f, 48.875f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 48.875f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 49f, 49.375f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 49f, 49.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(true, 49f, 49.375f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 49.125f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 49.375f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(true, 49.5f, 51f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 49.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 50f, 50.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 50f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 50.5f, 50.875f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 50.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 51f, 51.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 51f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 51f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 51.25f, 53f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.25f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 52f, 52.375f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 52f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 52.5f, 52.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 53f, 53.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 53f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 53.5f, 55f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 53.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 54f, 54.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 54f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 54.5f, 54.875f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 55f, 55.375f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 55f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 55f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 55.25f, 56.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 55.25f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 55.5f, 55.875f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 56f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 56f, 56.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 56.5f, 56.875f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 56.5f, 56.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 56.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 57f, 57.375f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 57f, 57.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 57f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 57f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 57.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 57.5f, 59f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 58f, 58.375f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 58f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 58.5f, 58.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 59f, 59.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 59f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 59f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 59.25f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 59.25f, 61f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 60f, 60.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 60f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 60.5f, 60.875f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 61f, 61.375f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 61f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 61.5f, 63f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 61.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 62f, 62.375f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 62f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 62.5f, 62.875f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 62.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 63f, 63.375f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 63f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 63f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 63.25f, 64.375f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 63.25f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 63.5f, 63.875f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 64f, 64.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 64f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 64.5f, 64.875f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 64.5f, 64.875f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 64.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 65f, 65.375f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 65f, 65.375f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 65f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 65f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 65.25f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 65.5f, 66f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 65.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 66f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 66f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 66.25f, 67f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 66.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 66.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 67f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 67f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 67.25f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 67.25f, 68f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 67.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 67.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 68f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 68.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 68.25f, 69.125f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 68.25f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 68.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 68.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 68.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 69f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 69f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 69.25f, 71.375f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 69.25f, 71.375f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 69.5f, 71.375f, "p"));
            input.Notes.Add(new Data.NoteInfo(true, 70.5f, 70.875f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 71f, 71.375f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 71.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 72.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 72.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 73.25f, 73.625f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 73.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 73.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 74f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 74.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 74.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 75.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 75.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 76f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 77f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 77.25f, 77.625f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 77.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 78f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 78.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 78.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 78.75f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 78.75f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 79f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 79f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 79f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 79.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 79.25f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 79.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 79.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 80f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 80.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 80.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 81f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 81.25f, 81.625f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 81.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 82.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 82.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 82.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 83.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 84f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 84.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 84.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 85f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 85.25f, 85.625f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 85.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 85.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 85.75f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 86f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 86f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 86.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 86.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 86.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 86.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 86.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 87f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 87f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 87.25f, 88.625f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 87.25f, 88.625f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 87.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 88f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 88.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 88.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 88.75f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 89f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 89f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 89f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 89.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 89.25f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 89.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 89.75f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 89.75f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 90f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 90f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 90f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 90.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 90.25f, 91.125f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 90.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 91f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 91.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 91.25f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 91.375f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 91.375f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 91.5f, 91.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 91.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 91.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 92f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 92f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 92.25f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 92.5f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 92.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 92.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 92.75f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 93f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 93f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 93f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 93.25f, 93.625f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 93.25f, 93.625f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 93.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 93.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93.75f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 94f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 94f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 94.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 94.25f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 94.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 94.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 94.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 94.75f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 95f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 95f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 95f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 95.25f, 96.5f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 95.25f, 96.5f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 95.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 96.75f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 97f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 97f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 97f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 97.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 97.25f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 97.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 97.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 97.75f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 98f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 98f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 98f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 98.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 98.25f, 98.875f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 98.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.25f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 99.25f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 99.375f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 99.375f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 99.5f, 99.875f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 99.5f, 99.875f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 99.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 100f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.25f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 100.25f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 100.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 100.5f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 100.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 100.75f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 100.75f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 101f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 101f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 101.25f, 101.625f, "p"));
            input.Notes.Add(new Data.NoteInfo(true, 101.25f, 103.375f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 101.25f, 103.375f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 101.75f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 102f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 102.25f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 102.5f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 102.75f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 103f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 103.25f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 103.812f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 103.875f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 103.937f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 104f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 104f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 104.187f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 104.375f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 104.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 104.687f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 104.75f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 105f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 105.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 105.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 105.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 105.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 105.812f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 105.937f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 106f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 106f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 106f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 106.187f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 106.187f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 106.375f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 106.375f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 106.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 106.625f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 106.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 106.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 106.937f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 107f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 107f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 107f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 107.187f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 107.187f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 107.375f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 107.375f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 107.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 107.625f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 107.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 107.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 108f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 108f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 108.187f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 108.187f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 108.375f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 108.375f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 108.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 108.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 108.625f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 108.875f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 109f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 109f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 109.187f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 109.25f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 109.437f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 109.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 109.5f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 109.625f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 109.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 109.875f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 110f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 110f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 110.125f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 110.187f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 110.375f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 110.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 110.5f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 110.5f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 110.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 110.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 110.875f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 110.875f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 111f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 111.125f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 111.187f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 111.375f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 111.375f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 111.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 111.625f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 111.687f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 111.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 111.812f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 111.875f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 111.937f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 112f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 112.062f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 112.125f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 112.187f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 112.25f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 112.312f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 112.375f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 112.437f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 112.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 112.5f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 112.5f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 112.75f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 112.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 112.875f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 112.875f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 113f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 113.125f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 113.125f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 113.375f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 113.375f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 113.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 113.625f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 113.687f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 113.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 113.812f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 113.875f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 113.937f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 114f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 114f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 114.062f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 114.125f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 114.187f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 114.25f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 114.312f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 114.375f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 114.437f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 114.5f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 114.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 114.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 114.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 114.75f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 114.937f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 114.937f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 115f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 115.125f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 115.125f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 115.375f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 115.375f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 115.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 115.625f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 115.75f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 115.875f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 116f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 116f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 116.25f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 116.375f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 116.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 116.5f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 116.562f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 116.625f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 116.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 116.812f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 116.875f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 117f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 117f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 117f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117.187f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 117.187f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 117.375f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 117.375f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 117.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 117.625f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 117.625f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117.687f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 117.687f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 117.75f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117.75f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 117.812f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 117.812f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 117.875f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117.875f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 117.937f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 117.937f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 118f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 118f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 118f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 118.062f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 118.062f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 118.125f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 118.125f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 118.187f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 118.187f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 118.25f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 118.25f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 118.312f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 118.312f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 118.375f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 118.375f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 118.437f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 118.437f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 118.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 118.5f, 119.5f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 118.75f, 119.5f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 119f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 119f, 119.5f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 119.5f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 119.5f, 0.2f, "j"));

        }
        else if (input.Difficulty.Equals("Extreme"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
    }
}
