using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class Northpole : MonoBehaviour {

    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 35;
        MusicInfo.name = "Northpole";
        MusicInfo.composer = "iMp";
        MusicInfo.visualizer = "PEENA";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "EZ2AC";
        normal.catchParase = normal_img;
        normal.level = 6;
        MusicInfo.list.Add(normal);

        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Endless";
        hard.level = 12;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Circulation";
        extreme.level = 3;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("EZ2AC"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 2.0f, "s"));
        }
        else if (input.Difficulty.Equals("Endless"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 4.566f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 4.737f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 4.909f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 5.08f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 5.252f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 5.423f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 5.595f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 5.766f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 7.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 7.309f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 7.48f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 7.652f, 8.423f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 10.052f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 10.223f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 10.395f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 10.566f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 10.737f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 10.909f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 11.08f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 11.252f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 12.623f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 12.795f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 12.966f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 13.137f, 13.909f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 15.366f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 15.537f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 15.709f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 15.88f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 15.88f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 16.052f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 16.223f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 16.395f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 16.395f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 16.566f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 16.737f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 16.909f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 17.423f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 17.766f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 18.109f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 18.109f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 18.28f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 18.452f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 18.623f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 18.623f, 19.395f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 19.137f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 19.652f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 20.166f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 20.509f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 20.852f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 21.023f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 21.195f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 21.366f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 21.366f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 21.537f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 21.709f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21.88f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 21.88f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 22.052f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 22.223f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 22.395f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 22.909f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 23.252f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 23.595f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 23.595f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23.766f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 23.937f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 24.109f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 24.109f, 24.88f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 24.623f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 25.137f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 25.652f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 25.995f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 26.337f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 26.509f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 26.68f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 26.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 26.852f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.023f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 27.195f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 27.366f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 27.366f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 27.537f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.709f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 28.052f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 28.395f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 28.48f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 28.566f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 28.737f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 29.08f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 29.252f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.423f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 29.423f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 29.595f, 30.366f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30.109f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 30.795f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 31.137f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 31.223f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 31.309f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 31.48f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 31.995f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 32.166f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.166f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 32.337f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 32.509f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 32.68f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 32.852f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.852f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.023f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 33.195f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33.537f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.88f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.966f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 34.052f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 34.223f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.566f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 34.737f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 34.909f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 34.909f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 35.08f, 35.852f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 35.595f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 36.28f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 36.623f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.709f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 36.795f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.966f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 37.309f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 37.48f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 37.652f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 37.652f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 37.823f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 37.823f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 37.995f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 38.166f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 38.337f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.337f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 38.337f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 38.509f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 38.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.852f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 39.023f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 39.366f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 39.366f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 39.452f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 39.537f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 39.709f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 39.709f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 40.052f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 40.052f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 40.223f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.395f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 40.395f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 40.566f, 41.337f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 40.566f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 41.08f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 41.08f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 41.595f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 41.766f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 42.109f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 42.109f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 42.195f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 42.28f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 42.452f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 42.452f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 42.795f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 42.966f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 43.137f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 43.309f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 43.309f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 43.48f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 43.652f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 43.823f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 43.823f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.823f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 43.995f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.166f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 44.337f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 44.509f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 44.852f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.852f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 44.937f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 45.023f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 45.195f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 45.195f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 45.537f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 45.537f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 45.709f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 45.88f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.88f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 46.052f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(true, 46.052f, 46.823f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 46.566f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 46.566f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 47.08f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 47.252f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 47.423f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 47.595f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 47.595f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 47.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 47.766f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 47.852f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 47.937f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 47.937f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 48.109f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 48.28f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 48.452f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 48.452f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 48.623f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 48.623f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 48.623f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 48.795f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 48.795f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 48.966f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 49.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 49.309f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 49.309f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 49.48f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 49.652f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49.995f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 50.337f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 50.423f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 50.509f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 50.68f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 51.023f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 51.023f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 51.195f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 51.366f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 51.366f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 51.366f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 51.537f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 51.537f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 52.052f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 52.052f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 52.395f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 52.566f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 52.737f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 53.08f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 53.166f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 53.252f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 53.423f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.766f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 53.937f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 53.937f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 54.109f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.109f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 54.109f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 54.28f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 54.28f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 54.452f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 54.623f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 54.795f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.795f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 54.966f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 55.48f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 55.823f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 55.909f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 55.995f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 56.166f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 56.509f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 56.509f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 56.68f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 56.852f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 56.852f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 56.852f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 57.023f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 57.023f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 57.537f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 57.88f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 58.052f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.223f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 58.566f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.652f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 58.737f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.909f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 59.252f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 59.423f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 59.423f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 59.595f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 59.595f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.595f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 59.766f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 59.766f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 59.937f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 60.109f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 60.28f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 60.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 60.452f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 60.623f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 60.966f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.309f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 61.395f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 61.48f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 61.995f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 61.995f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 62.166f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 62.337f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 62.337f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 62.337f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 62.509f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 62.509f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 63.023f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 63.023f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 63.366f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 63.537f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 63.709f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 64.052f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 64.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 64.223f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 64.395f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 64.737f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 64.909f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 64.909f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 65.08f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 65.08f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 65.08f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 65.252f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 65.252f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 65.423f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 65.595f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 65.766f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 65.766f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 65.937f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 66.109f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.452f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 66.795f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 66.88f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 66.966f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 67.137f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 67.48f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 67.48f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 67.652f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 67.823f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 67.823f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 67.823f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 67.995f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 67.995f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 68.509f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 68.852f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.023f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 69.195f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 69.537f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 69.623f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.709f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 69.88f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 70.223f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.395f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 70.395f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 70.566f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 70.566f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.737f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 70.737f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 70.909f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 71.08f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 71.252f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71.252f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 71.423f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 71.423f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 71.595f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 71.766f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 71.766f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 71.937f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 71.937f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 72.109f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 72.109f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 72.28f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 72.452f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 72.623f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 72.623f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 72.795f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 72.795f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 72.966f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 73.137f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 73.137f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 73.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 73.309f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 73.48f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 73.48f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 73.652f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 73.823f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.995f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 73.995f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 74.166f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.166f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 74.337f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 74.509f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.509f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 74.68f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 74.68f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.852f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.852f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 75.023f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 75.023f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 75.195f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 75.366f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 75.366f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.537f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 75.537f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 75.709f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 75.88f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.88f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 76.052f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.052f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 76.223f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 76.223f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 76.395f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 76.566f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 76.737f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 76.737f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.909f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 76.909f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 77.08f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 77.252f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.252f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 77.423f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 77.423f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 77.595f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.595f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 77.766f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 77.766f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 77.937f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 78.109f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.109f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 78.28f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 78.452f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.623f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 78.623f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 78.709f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 78.795f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.966f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 78.966f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 79.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 79.137f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 79.309f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 79.48f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 79.48f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 79.652f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 79.823f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 79.995f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 79.995f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 80.166f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 80.166f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80.337f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 80.337f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 80.509f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 80.509f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 80.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 80.852f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 80.852f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 81.023f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 81.023f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 81.195f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 81.366f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 81.366f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 81.537f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 81.537f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 81.709f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 81.709f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 81.88f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 82.052f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.223f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 82.223f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 82.395f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.395f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 82.566f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82.737f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 82.737f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 82.909f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82.909f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.08f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 83.08f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 83.252f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 83.423f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 83.595f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 83.595f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.766f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 83.766f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 83.937f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 84.109f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 84.109f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 84.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84.28f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 84.452f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 84.452f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 84.623f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 84.795f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 84.966f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 84.966f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 85.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 85.137f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 85.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.48f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 85.48f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 85.652f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 85.652f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.823f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 85.823f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 85.995f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 85.995f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 86.166f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 86.337f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 86.337f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 86.509f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 86.509f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 86.68f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 86.852f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 86.852f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 87.023f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 87.023f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 87.195f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 87.195f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 87.366f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.366f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 87.537f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.709f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 87.709f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.88f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.88f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 88.052f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 88.223f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 88.223f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 88.395f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 88.395f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 88.566f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 88.566f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 88.737f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 88.737f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 88.909f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 89.08f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 89.08f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 89.252f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 89.252f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 89.423f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 89.595f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 89.595f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 89.766f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 89.766f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 89.937f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 89.937f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 90.109f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 90.109f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 90.28f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 90.452f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 90.452f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 90.623f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 90.623f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 90.795f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 90.88f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 90.966f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 90.966f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 91.052f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 91.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 91.137f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 91.223f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 91.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 91.309f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 91.395f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 91.48f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 91.48f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 91.566f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 91.652f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 91.737f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 91.823f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 91.823f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 91.995f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 91.995f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 92.166f, 93.109f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 92.166f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 92.166f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92.337f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92.509f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 92.68f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 93.023f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 93.195f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 93.195f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 93.195f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 93.366f, 94.48f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 93.537f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 93.709f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 93.709f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 93.88f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 94.223f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 94.395f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.566f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 94.566f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 94.566f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(true, 94.737f, 95.852f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 94.909f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 94.909f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 95.08f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 95.252f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 95.423f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 95.766f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 95.937f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 95.937f, 96.195f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 95.937f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 96.28f, 96.88f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 96.28f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96.452f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 96.452f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96.623f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 96.966f, 97.566f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 96.966f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 97.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 97.309f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 97.309f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 97.48f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 97.652f, 98.595f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 97.652f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 97.652f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 97.823f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 97.995f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 98.166f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 98.509f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 98.68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 98.68f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 98.68f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 98.852f, 99.966f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 99.023f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.195f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 99.195f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.366f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 99.709f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 99.88f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.052f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 100.052f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 100.052f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(true, 100.223f, 101.337f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 100.395f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 100.395f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.566f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.737f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 100.909f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 101.252f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 101.423f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 101.423f, 101.68f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 101.423f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 101.766f, 102.023f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 101.766f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 101.937f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 101.937f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 102.109f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 102.109f, 102.366f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 102.452f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 102.452f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 102.623f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 102.623f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 102.709f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 102.795f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 102.795f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 102.795f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 102.966f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 103.137f, 104.08f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 103.137f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 103.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 103.309f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 103.48f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 103.652f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 103.995f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 104.166f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 104.166f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 104.166f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 104.337f, 105.452f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 104.509f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 104.68f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 104.68f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 104.852f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 105.195f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 105.366f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 105.537f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 105.537f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 105.537f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(true, 105.709f, 106.823f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 105.88f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 105.88f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 106.052f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 106.223f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 106.395f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 106.737f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 106.909f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 106.909f, 107.166f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 106.909f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 107.252f, 107.509f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 107.252f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 107.423f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 107.423f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 107.595f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 107.595f, 107.852f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 107.937f, 108.195f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 107.937f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 108.109f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 108.28f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 108.28f, 108.537f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 108.28f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 108.452f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 108.623f, 109.909f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 108.623f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 108.623f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 108.795f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 108.966f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 109.137f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 109.48f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 109.652f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 109.652f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 109.995f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 110.166f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 110.166f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 110.337f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 110.337f, 110.595f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 110.68f, 110.937f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 110.68f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 110.852f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 111.023f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 111.023f, 111.28f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 111.023f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(true, 111.366f, 111.966f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 111.366f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 111.366f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 111.537f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 111.709f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 111.88f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 112.223f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 112.395f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 112.395f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 112.395f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 112.737f, 112.995f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 112.737f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 112.909f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 112.909f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 113.08f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 113.08f, 113.337f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 113.423f, 113.852f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 113.423f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 113.595f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 113.766f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 113.766f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 113.937f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 114.109f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 114.109f, 115.395f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 114.109f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 114.28f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 114.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 114.452f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 114.452f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 114.623f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 114.795f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 114.966f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 114.966f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 115.137f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 115.137f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 115.309f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 115.48f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 115.48f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 115.652f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 115.652f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 115.823f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 115.823f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 115.995f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 116.166f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 116.252f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 116.337f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 116.337f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 116.337f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 116.509f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 116.509f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 116.68f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 116.68f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 116.852f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 116.852f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 117.023f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 117.023f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 117.195f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 117.195f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117.366f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 117.537f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 117.623f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 117.709f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 117.709f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 117.709f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 117.88f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 117.88f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 118.052f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 118.052f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 118.223f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 118.223f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 118.395f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 118.395f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 118.395f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 118.566f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 118.566f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 118.737f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 118.737f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 118.909f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 118.995f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 119.08f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 119.08f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 119.08f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 119.252f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 119.252f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 119.423f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 119.423f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 119.423f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 119.595f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 119.595f, 120.88f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 119.595f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 119.766f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 119.766f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 119.937f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 119.937f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 120.109f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 120.28f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 120.452f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 120.452f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 120.623f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 120.623f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 120.795f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 120.966f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 120.966f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 120.966f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 121.137f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 121.137f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 121.309f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 121.309f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 121.48f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 121.652f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 121.737f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 121.823f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 121.823f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 121.823f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 121.995f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 121.995f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 122.166f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 122.337f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 122.337f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 122.509f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 122.509f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 122.509f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 122.68f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 122.68f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 122.852f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 122.852f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 123.023f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 123.109f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 123.195f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 123.195f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 123.195f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 123.366f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 123.366f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 123.537f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 123.537f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 123.709f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 123.709f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 123.88f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 123.88f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 123.88f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 124.052f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 124.052f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 124.223f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 124.223f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 124.395f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 124.48f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 124.566f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 124.566f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 124.566f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 124.737f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 124.737f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 124.909f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 124.909f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 124.909f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 125.08f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 125.08f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 125.08f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 125.08f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 125.252f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 125.252f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 125.423f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 125.423f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 125.595f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 125.595f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 125.766f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 125.937f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 125.937f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 126.109f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 126.109f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 126.109f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 126.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 126.452f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 126.452f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 126.452f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 126.623f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 126.623f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 126.795f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 126.795f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 127.137f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 127.137f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 127.223f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 127.309f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 127.309f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 127.48f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 127.48f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 127.48f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 127.823f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 127.823f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 127.823f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 127.995f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 127.995f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 128.166f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 128.166f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 128.337f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 128.337f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 128.509f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 128.595f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 128.68f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 128.68f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 128.852f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 128.852f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 128.852f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 129.023f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 129.195f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 129.195f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 129.366f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 129.366f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 129.366f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 129.537f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 129.537f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 129.709f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 129.88f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 129.88f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 129.966f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 130.052f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 130.052f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 130.223f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 130.223f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 130.223f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 130.395f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 130.395f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 130.566f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 130.566f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 130.566f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 130.737f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 130.737f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 130.909f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 130.909f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 131.08f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 131.08f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 131.08f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 131.252f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 131.423f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 131.423f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 131.595f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 131.595f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 131.595f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 131.766f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 131.937f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 131.937f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 131.937f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 131.937f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 132.109f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 132.109f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 132.109f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 132.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 132.28f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 132.452f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 132.623f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 132.709f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 132.795f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 132.795f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 132.795f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 132.966f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 132.966f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 133.137f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 133.309f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 133.309f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 133.48f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 133.48f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 133.48f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 133.652f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 133.652f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 133.652f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 133.823f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 133.823f, 134.595f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 133.995f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 134.166f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 134.166f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 134.166f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 134.68f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 134.852f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 134.852f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 135.023f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 135.366f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 135.537f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 135.709f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 135.709f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 135.88f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 135.88f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 136.052f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 136.052f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 136.223f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 136.223f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 136.395f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 136.395f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 136.566f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 136.737f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 136.909f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 136.909f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 137.08f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 137.08f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 137.252f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 137.423f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 137.423f, 138.709f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 137.595f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 137.766f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 138.28f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 138.452f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 138.795f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 138.966f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 139.137f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 139.652f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 139.823f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 140.166f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 140.337f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 140.509f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 141.023f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 141.195f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 141.366f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 141.537f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 141.709f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 141.88f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 141.88f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 142.052f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 142.395f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 142.566f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 142.566f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 142.737f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 142.909f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 143.08f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 143.252f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 143.252f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 143.423f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 143.766f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 143.937f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 143.937f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 144.109f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 144.28f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 144.452f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 144.623f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 144.623f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 144.795f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 145.137f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 145.309f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 145.309f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 145.48f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 145.652f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 145.823f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 145.995f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 145.995f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 146.166f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 146.337f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 146.423f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 146.509f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 146.509f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 146.595f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 146.68f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 146.68f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 146.68f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 146.852f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 146.852f, 0.2f,";"));

        }
        else if (input.Difficulty.Equals("Circulation"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 2.0f, "s"));
        }
    }
}
