using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class Raise_Me_Up : MonoBehaviour {

    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 22;
        MusicInfo.name = "Raise Me Up";
        MusicInfo.composer = "Planetboom";
        MusicInfo.visualizer = "PUNEW, Super52";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "Normal";
        normal.catchParase = normal_img;
        normal.level = 6;
        MusicInfo.list.Add(normal);

        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Hard";
        hard.level = 12;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Extreme";
        extreme.level = 3;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("Normal"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 2f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 3.615f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 5.461f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 8.923f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 9.153f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.076f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 13.769f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 14.23f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 14.923f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 15.615f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 16.076f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 16.307f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 16.769f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 17.923f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 18.384f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 19.307f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 20.23f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 20.461f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 20.923f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 21.384f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 21.615f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 22.076f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.307f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 22.769f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.23f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.461f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23.923f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.153f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.615f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 25.076f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 25.307f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 26.461f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 26.692f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 26.923f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 27.846f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.538f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 28.769f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 29f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.692f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.153f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30.384f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 30.846f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 31.076f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 31.538f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 32f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.461f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 32.692f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 32.923f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 33.153f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 33.384f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 33.846f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 33.846f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 34.307f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 34.769f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 34.769f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 35.23f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 35.692f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 36.153f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 36.384f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.615f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 36.846f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 37.076f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 37.538f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 37.538f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 38f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 38.461f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 38.461f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 38.923f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 39.384f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 40.076f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.307f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 40.538f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 40.769f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 41f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 41.23f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 41.923f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 42.153f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 42.615f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 42.846f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 43.076f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 43.769f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 44f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 44.461f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 44.692f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 44.923f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 45.384f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 45.846f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 46.076f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 46.307f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 46.538f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 47f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 47.461f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 47.923f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 48.384f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 49.076f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 49.307f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 49.538f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 50f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 50.692f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 51.384f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 51.846f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 52.307f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 52.769f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.23f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 53.461f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 53.692f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 53.923f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.384f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.846f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 55.307f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 55.769f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 56.461f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 56.692f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 56.923f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 57.384f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 57.615f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 58.076f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 58.538f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 59f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 59.461f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 59.923f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 60.384f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 60.615f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 60.846f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 61.076f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 61.538f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 61.769f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 62.461f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 62.923f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 63.384f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 63.615f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 64.307f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 64.769f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 65.23f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 65.461f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 66.153f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 66.615f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 67.076f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 67.307f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 68f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 68.461f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 68.923f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 69.153f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 69.846f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 70.307f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 70.769f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 71.23f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71.692f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72.153f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 72.615f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 72.846f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 73.076f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 73.538f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 74f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 74.461f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.692f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 74.923f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 75.384f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.384f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 75.846f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 76.076f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 76.307f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 76.769f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 77f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 77.23f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 77.461f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 77.692f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 78.153f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 78.615f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 78.846f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 79.538f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 80f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 80.23f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 80.461f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80.576f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 80.692f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80.923f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 81.153f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 81.384f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 81.846f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.076f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.307f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.538f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 83f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.23f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 83.692f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 83.923f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 84.153f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84.384f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 84.615f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84.846f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 85.076f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 85.307f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 85.538f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 85.538f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 86.23f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 86.461f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 86.461f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 86.923f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 87.153f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 87.384f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.384f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 87.615f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 88.307f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 88.307f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 88.769f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 89.23f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 89.692f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 90.153f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 90.615f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 91.076f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 91.538f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 92f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 92.23f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 92.461f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92.923f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93.846f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 94.076f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 94.307f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 94.769f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.769f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 95.23f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 95.692f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 95.807f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 96.153f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 96.384f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 97.538f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 98f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 98.461f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 98.692f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 99.384f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 99.615f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 99.615f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 99.846f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 101.23f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 101.461f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 101.692f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 102.153f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 102.153f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 102.615f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 103.076f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 103.076f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 103.538f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 104f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 104f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 104.461f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 104.923f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 104.923f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 105.384f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 105.846f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 106.076f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 106.307f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 106.538f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 106.769f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 107.23f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 107.692f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 107.923f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 108.615f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 108.846f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 109.538f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 110.23f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 110.692f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 111.153f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 111.269f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 111.384f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 112.307f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 112.307f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 112.769f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 113.23f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 113.461f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 114.153f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 114.384f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 114.615f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 115.076f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 116f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 116f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 116.23f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 116.461f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 116.923f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117.153f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 117.846f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 118.307f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 118.307f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 118.769f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 118.769f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 119.23f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 119.23f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 119.692f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 119.692f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 120.153f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 120.153f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 120.615f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 120.615f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 121.076f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 121.076f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 121.538f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 121.538f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 121.769f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 121.769f, 0.2f, "d"));

        }
        else if (input.Difficulty.Equals("Hard"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
        else if (input.Difficulty.Equals("Extreme"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
    }
}
