using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class Remember : MonoBehaviour {

    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 31;
        MusicInfo.name = "Remember";
        MusicInfo.composer = "Lin-G";
        MusicInfo.visualizer = "BBANG, woodstock";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "Normal";
        normal.catchParase = normal_img;
        normal.level = 6;
        MusicInfo.list.Add(normal);

        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Hard";
        hard.level = 12;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Extreme";
        extreme.level = 3;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("Normal"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 3.61f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 4.41f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 4.61f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 5.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 6.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 6.21f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 6.61f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 7.61f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 7.81f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 8.21f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 8.41f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 8.61f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 8.81f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 9.01f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 9.21f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 9.51f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 9.81f, 11.51f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 13.21f, 14.71f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 15.61f, 16.31f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 16.41f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 16.81f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 17.01f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 17.81f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 18.01f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 18.41f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 18.61f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 19.21f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 19.41f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 19.61f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 19.61f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 20.01f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 20.21f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 21.01f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 21.21f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 21.61f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 21.81f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 21.81f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 22.61f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 22.61f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 22.71f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23.21f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 23.41f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.21f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.41f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 24.81f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 25.01f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 25.41f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 25.61f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.01f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 26.41f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.61f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 27.01f, 27.71f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 27.81f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 28.01f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 28.21f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.41f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 28.61f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 28.81f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 29.21f, 30.71f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 31.21f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 31.41f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 31.81f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.41f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 32.61f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.81f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33.01f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.41f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.21f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 34.41f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 34.61f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 35.01f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 35.41f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 35.61f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 36.61f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 36.81f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 37.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 37.21f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 37.61f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 37.81f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 38.21f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 38.81f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 39.21f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 39.41f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 39.81f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 40.21f, 41.01f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 41.21f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 41.31f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 41.41f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 41.51f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 41.61f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 41.71f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 41.81f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 41.91f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 42.01f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 42.21f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 42.41f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 42.61f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 42.81f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 43.01f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 43.21f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 43.41f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 43.61f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 43.81f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 44.21f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.41f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 44.61f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 44.81f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 45.01f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 45.21f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 45.41f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.61f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 45.81f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 46.01f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 46.21f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 46.41f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 46.61f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 46.81f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.01f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 47.21f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 47.41f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 47.61f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.61f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 47.81f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.81f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 48.01f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 48.61f, 48.91f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 49.01f, 49.91f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 50.21f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 50.41f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 50.61f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 51.01f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 51.41f, 52.11f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 51.41f, 52.11f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 52.21f, 53.11f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 52.21f, 53.11f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 53.21f, 53.71f, ";"));
            input.Notes.Add(new Data.NoteInfo(true, 53.21f, 53.71f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 53.81f, 54.51f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 53.81f, 54.51f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 55.21f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 55.61f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 55.81f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 56.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 56.21f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 56.61f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 57.01f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 57.61f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 57.81f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 58.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.41f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.61f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 59.21f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.41f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 59.61f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 59.81f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 60.01f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 60.21f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 60.61f, 61.11f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 61.21f, 61.71f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 61.21f, 61.71f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 61.81f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 62.21f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 62.61f, 63.21f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 62.61f, 63.21f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 63.41f, 64.01f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 63.41f, 64.01f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 64.21f, 64.81f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 64.21f, 64.81f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 65.01f, 65.51f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 65.01f, 65.51f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 65.61f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 66.01f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 66.21f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 66.41f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.61f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 67.01f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 67.41f, 69.11f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 67.41f, 69.11f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 69.21f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 69.41f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 69.61f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 69.61f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 69.81f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 70.01f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.41f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 70.41f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 70.61f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 70.81f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 71.01f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 71.21f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 71.21f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.41f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 71.61f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 72.01f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 72.01f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72.21f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 72.41f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72.61f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 72.81f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 72.81f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 73.01f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.21f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 73.41f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.61f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 73.61f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 73.81f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.01f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 74.21f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 74.41f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 74.61f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.81f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 75.01f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 75.21f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.21f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 75.61f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 75.81f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.01f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 76.21f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 76.61f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 76.81f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 77.01f, 77.31f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 77.41f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 77.61f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 77.71f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.81f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 78.01f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 78.21f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.61f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 78.81f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 79.01f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 79.21f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 79.41f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 79.61f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 79.81f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80.01f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 80.21f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 80.41f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80.61f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 80.81f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 81.01f, 81.31f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 81.41f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 81.61f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 81.81f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.01f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 82.21f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82.41f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 82.41f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.61f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 82.81f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 83.21f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 83.21f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.41f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.61f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 83.81f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84.01f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 84.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 84.21f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 84.41f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 84.61f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 84.81f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 84.81f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 85.01f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 85.21f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 85.41f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 85.61f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 85.61f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 85.81f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 86.01f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 86.21f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 86.41f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 86.41f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 86.61f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 86.81f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 87.21f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 87.21f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 87.41f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 87.81f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 87.81f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 88.01f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 88.21f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 88.21f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 88.41f, 88.71f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 89.01f, 89.31f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 89.41f, 89.71f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 89.81f, 90.31f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 89.81f, 90.31f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 90.61f, 91.11f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 90.61f, 91.11f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 91.41f, 91.91f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 91.41f, 91.91f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 92.21f, 92.71f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 92.21f, 92.71f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 92.81f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 93.21f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 93.41f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93.61f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 93.81f, 94.11f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 94.21f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 94.61f, 96.11f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 94.61f, 96.11f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 94.61f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 96.21f, 96.91f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 96.21f, 96.91f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 97.01f, 97.71f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 97.01f, 97.71f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 97.81f, 98.51f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 97.81f, 98.51f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 98.61f, 99.11f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 98.61f, 99.11f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 99.21f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 99.61f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 99.81f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 100.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 100.21f, 100.51f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 100.61f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 101.01f, 102.71f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 103.01f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 103.21f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 103.41f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 103.61f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 103.81f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 104.01f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 104.21f, 105.91f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 104.21f, 105.91f, "s"));


        }
        else if (input.Difficulty.Equals("Hard"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));

        }
        else if (input.Difficulty.Equals("Extreme"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
    }

}
