using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class Someday : MonoBehaviour {

    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 30;
        MusicInfo.name = "Someday";
        MusicInfo.composer = "NieN";
        MusicInfo.visualizer = "Chris";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "Normal";
        normal.catchParase = normal_img;
        normal.level = 6;
        MusicInfo.list.Add(normal);

        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Hard";
        hard.level = 12;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Extreme";
        extreme.level = 3;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("Normal"))
        {
            input.Notes.Add(new Data.NoteInfo(true, 2.464f, 3.016f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 3.126f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 3.347f, 3.677f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 3.788f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 4.008f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 4.229f, 4.56f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 4.67f, 5.001f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 5.111f, 5.442f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 5.552f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 5.773f, 7.317f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 7.538f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 7.538f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 7.979f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 7.979f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 8.42f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 8.42f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 8.861f, 9.413f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 8.861f, 9.413f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 9.523f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 9.523f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 11.067f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 11.177f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 11.288f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 11.508f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 11.729f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 11.95f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 12.611f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.052f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 13.052f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 13.273f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 13.714f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 14.817f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 15.038f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 15.258f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 15.479f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 15.92f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 16.141f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 16.582f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 16.582f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 17.905f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 17.905f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 18.347f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 18.347f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 19.67f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 19.67f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 20.111f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 20.111f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 21.876f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 21.876f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 22.758f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.758f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.2f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23.2f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 23.641f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 23.641f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 23.861f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 24.082f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.302f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 24.744f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.964f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 25.185f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 25.405f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 25.626f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.067f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 26.288f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 26.508f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 26.729f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.95f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.17f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 27.17f, 27.942f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.494f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 28.935f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.935f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 29.376f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 29.376f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 29.817f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.817f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 30.258f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 30.258f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 30.7f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 30.7f, 32.133f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 32.244f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 32.354f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 32.464f, 34.119f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 34.229f, 35.883f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 34.45f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 34.67f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 35.001f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 35.332f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 35.663f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 35.994f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 35.994f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 36.325f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 36.325f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 36.655f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 36.655f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 37.758f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 37.758f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 38.2f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.42f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.641f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.861f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.861f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 39.302f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 39.523f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 39.523f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 39.744f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 39.964f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.185f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 40.185f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.626f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 40.847f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 41.067f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 41.288f, 41.839f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 41.288f, 41.839f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 41.95f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 42.17f, 42.722f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 42.17f, 42.722f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 42.832f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 43.052f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 43.052f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.494f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 43.935f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 44.155f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.266f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 44.376f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.486f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 44.597f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.707f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 44.817f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 44.817f, 45.589f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 45.7f, 46.03f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 45.7f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 46.141f, 46.472f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 46.141f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 46.582f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 46.582f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 46.913f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 46.913f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 47.244f, 48.236f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 47.244f, 48.236f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 48.347f, 49.119f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 48.788f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 49.229f, 50.001f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49.67f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 50.111f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 50.111f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 50.442f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 50.442f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 50.773f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 50.773f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 51.214f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.435f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 51.876f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 51.876f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 52.317f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 52.538f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 52.758f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.2f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 53.641f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 54.082f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 54.523f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 54.964f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 55.185f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 55.405f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 55.847f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 56.067f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 56.288f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 56.729f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 57.17f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 57.611f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 58.052f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 58.494f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 58.494f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 58.714f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 58.714f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 58.935f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 58.935f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 59.266f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 59.597f, 60.589f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 60.699f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 60.699f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 61.03f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 61.361f, 62.354f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 62.464f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 62.464f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 62.795f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 62.795f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 63.126f, 63.898f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 63.126f, 63.898f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 64.008f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 64.119f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 64.229f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 64.229f, 65.663f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 64.891f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 65.552f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 65.994f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 65.994f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 66.435f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 66.435f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.876f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 67.317f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 67.317f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 67.758f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 68.199f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 68.199f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 68.641f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 68.641f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.082f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 69.082f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 69.523f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.523f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 69.964f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.964f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 70.405f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 70.405f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 70.847f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71.288f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 71.288f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 71.508f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 71.729f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 71.949f, 72.501f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 72.611f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 72.611f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 73.052f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 73.052f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 73.494f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 73.714f, 74.266f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 74.376f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.376f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.817f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 74.817f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 75.258f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 75.479f, 76.03f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 76.141f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 76.582f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 76.582f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 76.802f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.023f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.244f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.464f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 77.685f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 77.905f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.126f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 78.236f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 78.347f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 78.347f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.677f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 79.008f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 79.229f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 79.229f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 79.56f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 79.891f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 80.111f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 80.111f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80.552f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 80.773f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 80.994f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81.214f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81.435f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81.655f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81.766f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81.876f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 81.876f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 82.317f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 82.317f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 82.758f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82.758f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.199f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.199f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 83.641f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.641f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 84.082f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 84.302f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84.523f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 84.744f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 84.964f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.185f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 85.295f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.405f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 85.405f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 85.626f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 85.847f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 86.067f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 86.288f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 86.508f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 86.729f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 86.729f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 86.949f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 87.17f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 87.17f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 87.391f, 88.604f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 88.714f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 88.824f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 88.935f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 88.935f, 90.589f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 90.699f, 92.133f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 90.699f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 91.141f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 91.361f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 91.582f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92.023f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 92.464f, 92.795f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 92.905f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 93.126f, 93.457f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93.567f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 93.677f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 93.788f, 94.119f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 94.229f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 94.229f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 94.67f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 94.67f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 94.891f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 95.111f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 95.332f, 95.663f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 95.332f, 95.663f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 95.773f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 95.883f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 95.994f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 95.994f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 96.214f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 96.435f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 96.655f, 96.986f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 96.655f, 96.986f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 97.097f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 97.317f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 97.538f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 97.758f, 98.31f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 97.758f, 98.31f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 98.42f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 98.53f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 98.641f, 99.192f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 98.641f, 99.192f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 99.302f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 99.413f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 99.523f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 99.523f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 99.964f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 99.964f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 100.405f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 100.405f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 100.626f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 100.736f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 100.847f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 100.847f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 101.288f, 101.839f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 101.288f, 101.839f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 102.17f, 102.501f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 102.17f, 102.501f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 102.611f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 102.832f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 103.052f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 103.052f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 103.383f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 103.383f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 103.714f, 104.486f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 103.714f, 104.486f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 104.597f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 104.707f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 104.817f, 105.369f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 105.479f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 105.589f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 105.699f, 106.251f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 106.361f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 106.472f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 106.582f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 106.582f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 106.913f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 107.133f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 107.464f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 107.464f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 107.685f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 107.795f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 107.905f, 108.236f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 107.905f, 108.236f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 108.347f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 108.347f, 109.119f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 108.788f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 109.008f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(true, 109.229f, 109.78f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 109.449f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 109.56f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 109.67f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 110.111f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 110.111f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 110.552f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 110.773f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 110.994f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 111.214f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 111.324f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 111.435f, 111.766f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 111.435f, 111.766f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 111.876f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 111.876f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 112.097f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 112.097f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 112.538f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 112.538f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 112.979f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 112.979f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 113.199f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 113.42f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 113.42f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 113.861f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 113.861f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 114.082f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 114.302f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 114.302f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 114.744f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 114.744f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 114.964f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 114.964f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 115.185f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 115.185f, 116.839f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 116.949f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(true, 116.949f, 118.383f, "p"));
        }
        else if (input.Difficulty.Equals("Hard"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
        else if (input.Difficulty.Equals("Extreme"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
    }
}
