using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class Supersonic2011 : MonoBehaviour {

    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 27;
        MusicInfo.name = "Supersonic2011";
        MusicInfo.composer = "PlanetBoom";
        MusicInfo.visualizer = "Pentavision Sound LAB";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "Normal";
        normal.catchParase = normal_img;
        normal.level = 6;
        MusicInfo.list.Add(normal);

        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Hard";
        hard.level = 12;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Extreme";
        extreme.level = 3;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("Normal"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 1.65f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 2.055f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 2.46f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 2.866f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 3.474f, 3.981f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 4.082f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 4.285f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 4.487f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 4.69f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 4.893f, 5.197f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 5.501f, 6.109f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 6.717f, 7.122f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 7.325f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 7.528f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 7.731f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 7.933f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 8.339f, 9.048f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 9.555f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 9.758f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 9.96f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 10.163f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 10.366f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 10.771f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 11.177f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 11.379f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 11.582f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 11.785f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 11.987f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 12.798f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 13.001f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 13.204f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 13.406f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.609f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 13.812f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 14.014f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 14.217f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 14.42f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 14.622f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 14.825f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 15.028f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 15.231f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 16.244f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 16.447f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 16.649f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 17.055f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 17.258f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 17.46f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 17.866f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 18.068f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 18.271f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 18.677f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 18.879f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 19.082f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 19.487f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 19.69f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 19.893f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 20.298f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 20.501f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 20.704f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 21.109f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 21.312f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21.514f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 21.92f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 22.122f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 22.325f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 22.731f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 22.933f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23.136f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 23.541f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.744f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 23.947f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 24.352f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.555f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.758f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 25.163f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 25.366f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 25.568f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 25.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.177f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 26.379f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 26.785f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 26.987f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.19f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 27.595f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 27.798f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 28.001f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 28.406f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 28.609f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.812f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 29.217f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 29.622f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 30.028f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 30.231f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30.332f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 30.433f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 30.636f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 30.839f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 31.244f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 31.649f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 31.649f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 31.852f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.055f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 32.055f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.46f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.866f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33.271f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 33.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.575f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 33.677f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33.879f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 34.082f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.487f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 34.893f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.893f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 35.095f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 35.298f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 35.298f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 35.704f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 36.109f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 36.514f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 36.616f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 36.717f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 36.92f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 37.325f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 37.731f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 38.136f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 38.136f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 38.339f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.44f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 38.541f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 38.947f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 39.352f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 39.758f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 39.859f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 39.96f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 40.163f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 40.568f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 40.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 41.379f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 41.379f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 41.582f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 41.683f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 41.785f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 42.19f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.393f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 42.595f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.798f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.001f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 43.204f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.406f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 43.609f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.812f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 44.014f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.217f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 44.42f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.622f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 44.825f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.028f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 45.231f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.433f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 45.636f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 45.839f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 46.041f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 46.244f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 46.447f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 46.649f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 46.852f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 47.055f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 47.258f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 47.46f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 47.663f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 47.866f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 48.068f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 48.271f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 48.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 48.677f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 48.879f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 49.082f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 49.285f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 49.487f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 49.69f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49.893f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 50.095f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 50.298f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 50.501f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 50.704f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 50.906f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 51.109f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 51.312f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.514f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 51.717f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.92f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 52.122f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 52.325f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 52.528f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 52.731f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 52.933f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 53.136f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 53.339f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 53.541f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 53.744f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.947f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 54.149f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 54.352f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 54.555f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 54.758f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 54.96f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 55.163f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 55.366f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 55.568f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 55.771f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 55.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 56.177f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 56.379f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 56.379f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 56.582f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 56.582f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 56.785f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 56.987f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 57.19f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 57.393f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 57.595f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 57.798f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.001f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 58.001f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 58.204f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 58.204f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 58.406f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 58.609f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 58.812f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 59.014f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 59.217f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.217f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 59.42f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.42f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 59.622f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 59.622f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 59.825f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 59.825f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 60.028f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 60.231f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 60.433f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 60.636f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 60.839f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 60.839f, 61.649f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 61.041f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 61.244f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.447f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 61.649f, 62.46f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 61.649f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 61.852f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 62.055f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 62.258f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 62.46f, 63.271f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 63.271f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 63.677f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 64.082f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 64.285f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 64.69f, 65.399f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 65.501f, 65.805f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 65.906f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.109f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 66.312f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 66.514f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.92f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 67.325f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 67.528f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 67.933f, 68.643f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 68.744f, 69.048f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 69.149f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 69.352f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 69.555f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 69.758f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 70.163f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 70.568f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.771f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 71.177f, 71.886f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 71.987f, 72.291f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 72.393f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 72.595f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72.798f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 73.001f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.406f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.812f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 74.014f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 74.42f, 75.129f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 75.231f, 75.535f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 75.636f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.839f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 76.041f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 76.244f, 76.954f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 77.055f, 77.562f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.663f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 78.068f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 78.271f, 78.981f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 79.487f, 80.197f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 80.298f, 80.805f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 80.906f, 81.413f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 81.514f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 81.717f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 81.92f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 82.325f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 82.731f, 83.237f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 83.541f, 84.048f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 84.149f, 84.454f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 84.555f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 84.758f, 85.467f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 85.974f, 86.886f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 86.987f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 87.393f, 88.508f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 89.217f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 89.42f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 89.622f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 89.622f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 90.028f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 90.231f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 90.433f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 90.433f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 90.839f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 91.041f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 91.244f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 91.244f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 91.649f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 91.852f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 92.055f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 92.055f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92.46f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 92.663f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 92.866f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 92.866f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 93.271f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 93.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 93.677f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 93.677f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.082f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 94.285f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 94.487f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 94.487f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.893f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 95.095f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 95.298f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 95.298f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 95.704f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 95.906f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 96.109f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 96.109f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96.514f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 96.717f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 96.92f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 96.92f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 97.325f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 97.528f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 97.731f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 97.731f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 98.136f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 98.339f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 98.541f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 98.541f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 98.947f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 99.149f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 99.352f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.352f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 99.758f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 99.96f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 100.163f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 100.163f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.568f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 100.771f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 100.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 100.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 101.379f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101.582f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 101.785f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 101.785f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 102.19f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 102.19f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 102.595f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 102.595f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 103.001f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 103.001f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 103.204f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 103.204f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 103.609f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 103.609f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 104.42f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 104.42f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 104.825f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 104.825f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 105.028f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 105.028f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 105.231f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 105.231f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 105.636f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 105.636f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 106.244f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 106.244f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 106.447f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 106.447f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 106.852f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 106.852f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 107.258f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 107.258f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 107.663f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 107.663f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 108.068f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 108.068f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 108.271f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 108.271f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 108.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 108.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 109.082f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 109.082f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 109.487f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 109.487f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 109.69f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 109.69f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 110.095f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 110.095f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 110.906f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 110.906f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 111.312f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 111.312f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 111.514f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 111.514f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 111.717f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 111.717f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 112.325f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 112.325f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 112.731f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 112.731f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 112.933f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 112.933f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 113.339f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 113.339f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 113.744f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 113.744f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 114.149f, 114.96f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 114.149f, 114.96f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 115.163f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 115.568f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 115.771f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 115.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 116.379f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 116.582f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 116.987f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 117.19f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117.595f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 117.798f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 118.001f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 118.406f, 118.913f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 119.217f, 119.724f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 119.825f, 120.94f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 121.447f, 121.954f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 122.055f, 122.359f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 122.46f, 122.967f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 123.068f, 123.778f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 123.879f, 124.589f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 124.893f, 125.399f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 125.501f, 126.008f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 126.109f, 127.224f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 127.325f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 127.731f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 127.933f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 128.136f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 128.44f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 128.744f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 128.947f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 129.251f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 129.555f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 129.758f, 132.697f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 132.798f, 0.2f,"a"));
            input.Notes.Add(new Data.NoteInfo(false, 132.798f, 0.2f, ";"));

        }
        else if (input.Difficulty.Equals("Hard"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
        else if (input.Difficulty.Equals("Extreme"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
    }
}
