using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class Take_On_Me : MonoBehaviour {

    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 25;
        MusicInfo.name = "Take on Me";
        MusicInfo.composer = "Cuve";
        MusicInfo.visualizer = "AJ";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "Normal";
        normal.catchParase = normal_img;
        normal.level = 6;
        MusicInfo.list.Add(normal);

        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Hard";
        hard.level = 12;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Extreme";
        extreme.level = 3;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("Normal"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.6f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 0.834f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 1.42f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 2.006f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 2.709f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 3.646f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 4.584f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 5.756f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 6.225f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 6.459f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 6.928f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 7.396f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 7.631f, 8.1f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 8.1f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 8.568f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 8.568f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 9.037f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 9.506f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 9.506f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 9.506f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 9.74f, 9.975f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 9.975f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 10.443f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 10.678f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 11.029f, 11.498f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 11.615f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 11.85f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 12.084f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 12.318f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 12.553f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 13.021f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 13.256f, 13.725f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 13.725f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.959f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 14.428f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 14.896f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 15.131f, 15.6f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 15.6f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 16.068f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 16.068f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 16.537f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 17.006f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 17.006f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 17.006f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 17.24f, 17.475f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 17.475f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 17.943f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 18.178f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 18.529f, 18.998f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 19.115f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 19.35f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 19.467f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 19.584f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 19.818f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 20.287f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 20.756f, 21.225f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 21.225f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21.459f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 21.576f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 21.693f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 21.928f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 22.279f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 22.396f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 22.631f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 22.865f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.217f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 23.334f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23.568f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 23.568f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 23.803f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23.92f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 24.037f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 24.271f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.506f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 24.506f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 24.975f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 24.975f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 25.209f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 25.326f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 25.443f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 25.678f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 25.912f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.146f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 26.381f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 26.615f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 26.85f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 26.967f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 27.318f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.787f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.904f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 28.256f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 28.256f, 28.725f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 28.725f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 28.959f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 29.428f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.662f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 29.896f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.365f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 30.6f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.834f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 31.068f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 31.303f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 31.537f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 31.771f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 32.006f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 32.24f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 32.475f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 32.709f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 32.943f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 33.178f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.412f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 33.646f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 33.881f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 34.115f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 34.35f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 34.467f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 34.818f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.935f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 35.053f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 35.521f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 35.99f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 36.225f, 36.81f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 36.928f, 37.865f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 38.1f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 38.334f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 38.451f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 38.568f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 39.037f, 39.623f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 39.975f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 40.443f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 40.443f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 40.912f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 41.381f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 41.381f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 41.85f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 42.318f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 42.435f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 42.787f, 43.49f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 43.49f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 43.725f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 43.725f, 44.31f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 44.428f, 45.482f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 45.6f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 45.834f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.951f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 46.068f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 46.303f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 46.537f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 46.771f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 47.006f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 47.006f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 47.24f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 47.475f, 48.412f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 48.881f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49.115f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 49.35f, 49.935f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 50.053f, 50.756f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 51.225f, 51.81f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 51.928f, 52.982f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 53.1f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 53.334f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 53.451f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 53.568f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 53.803f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 53.92f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 54.037f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 54.271f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.389f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 54.506f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 54.74f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 54.975f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.209f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 55.443f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 55.678f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.912f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 56.146f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 56.381f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 56.615f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 56.85f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 57.084f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 57.201f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 57.318f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 57.553f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 57.67f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 57.787f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 58.021f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 58.139f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 58.256f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 58.49f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 58.725f, 59.31f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 59.428f, 60.482f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 60.6f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 60.834f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 60.951f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 61.068f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 61.303f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 61.42f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 61.537f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.771f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 61.889f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 62.006f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 62.24f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 62.475f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 62.709f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 62.943f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 63.178f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 63.412f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 63.646f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 63.881f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 64.115f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 64.35f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 64.584f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 64.818f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 64.818f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 65.287f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 65.287f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 65.756f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 65.756f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 66.225f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 66.459f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 66.693f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 66.928f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 67.162f, 67.982f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 68.1f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 68.1f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 68.568f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 68.92f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 69.271f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 69.389f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 69.506f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 69.74f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 69.975f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 70.092f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 70.209f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 70.326f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 70.678f, 71.146f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 71.381f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 71.381f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 71.85f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 72.084f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 72.201f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 72.318f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 72.553f, 72.787f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 73.021f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 73.256f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 73.49f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 73.607f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.725f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 73.959f, 74.662f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 74.896f, 75.482f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.834f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 75.951f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 76.068f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.185f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 76.771f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 76.889f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.006f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 77.24f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 77.475f, 77.943f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.178f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 78.295f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 78.646f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 78.764f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 79.35f, 79.935f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 80.053f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 80.17f, 80.639f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 80.756f, 81.576f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 81.928f, 82.514f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 81.928f, 82.514f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 82.631f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 82.631f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 83.1f, 83.685f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 83.803f, 84.74f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 84.975f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 85.209f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.326f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 85.443f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 85.912f, 86.498f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 86.85f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 87.318f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 87.318f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 87.787f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 88.256f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 88.256f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 88.725f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 89.193f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 89.31f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 89.662f, 90.365f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 90.365f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 90.6f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 90.6f, 91.185f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 91.303f, 92.357f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 92.475f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 92.709f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 92.826f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 92.943f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 93.178f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 93.412f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93.646f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 93.881f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93.881f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.115f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 94.35f, 95.287f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 95.756f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 95.99f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 96.225f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 96.459f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 96.576f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(true, 96.928f, 97.514f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 98.568f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 98.685f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 98.92f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 99.154f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 99.506f, 99.857f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 99.975f, 10.032f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 100.443f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 100.912f, 101.732f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101.85f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 102.084f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 102.201f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 102.318f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 102.553f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 102.787f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 103.021f, 103.607f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 103.725f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 103.842f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 104.076f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 104.31f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 104.545f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 104.779f, 105.482f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 105.6f, 106.185f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 106.303f, 107.123f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 107.475f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 107.592f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 107.709f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 107.826f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 108.06f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 108.295f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 108.529f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 108.764f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 108.881f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 108.998f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 109.35f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 109.584f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 109.701f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 109.818f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 109.935f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 110.287f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 110.404f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 110.639f, 111.107f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 111.225f, 112.045f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 112.162f, 112.982f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 113.1f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 113.334f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 113.568f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 113.803f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 114.037f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 114.271f, 114.857f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 115.209f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 115.912f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 116.381f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 116.615f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 116.967f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 117.787f, 0.2f, "j"));

        }
        else if (input.Difficulty.Equals("Hard"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
        else if (input.Difficulty.Equals("Extreme"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.0f, 0.2f, "s"));
        }
    }
}
