using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Video;
public class You_Sky : MonoBehaviour {

    public AudioClip clip;
    public VideoClip bga;
    public VideoClip bga_blur;
    public Texture normal_img;
    public Texture hard_img;
    public Texture extreme_img;


    Data.MusicInfo MusicInfo = new Data.MusicInfo();
    void Start()
    {
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
    }
    public Data.MusicInfo GetInfo()
    {
        MusicInfo.key = 37;
        MusicInfo.name = "You&Sky";
        MusicInfo.composer = "JIMMie";
        MusicInfo.visualizer = "Default";
        MusicInfo.music = clip;
        MusicInfo.bga_blur = bga_blur;
        MusicInfo.bga = bga;
        MusicInfo.list = new List<Data.Playdata>();
        ListInit();

        return MusicInfo;
    }
    void ListInit()
    {
        //int comboCalc = 0;
        Data.Playdata normal = new Data.Playdata();
        normal.Difficulty = "Normal";
        normal.catchParase = normal_img;
        normal.level = 4;
        MusicInfo.list.Add(normal);

        //comboCalc = 0;
        Data.Playdata hard = new Data.Playdata();
        hard.Difficulty = "Hard";
        hard.level = 5;
        hard.catchParase = hard_img;
        MusicInfo.list.Add(hard);

        //comboCalc = 0;
        Data.Playdata extreme = new Data.Playdata();
        extreme.Difficulty = "Extreme";
        extreme.level = 20;
        extreme.catchParase = extreme_img;
        MusicInfo.list.Add(extreme);
    }
    public void getNote(Data.Playdata input)
    {
        CreateNote(input);
        input.max_combo = input.Notes.Count;
    }
    void CreateNote(Data.Playdata input)
    {
        input.Notes = new List<Data.NoteInfo>();
        if (input.Difficulty.Equals("Normal"))
        {
            input.Notes.Add(new Data.NoteInfo(true, 0.974f, 1.84f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 1.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 2.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 3.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 3.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 3.974f, 5.349f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 5.474f, 5.849f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 5.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 6.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 6.599f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 6.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 7.224f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 7.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 7.974f, 8.849f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 9.474f, 9.849f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 9.974f, 10.84f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 11.224f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 11.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 11.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 11.974f, 13.099f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 13.224f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 13.599f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 13.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 13.849f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 13.974f, 14.599f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 14.724f, 15.099f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 15.224f, 15.599f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 15.974f, 17.849f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 17.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 17.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 18.349f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 18.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 18.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 19.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 19.474f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 19.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 20.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 20.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 20.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 21.099f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 21.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 21.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 22.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 22.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 22.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 23.474f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 23.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 25.099f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 25.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 25.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 25.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.349f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 27.474f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 27.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 29.099f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 29.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 31.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 31.474f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 31.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 32.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 32.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 32.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 33.099f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 33.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 34.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 34.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 35.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 35.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 35.474f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 35.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.849f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 37.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 37.849f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 37.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 38.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 38.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 39.224f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 39.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 39.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 39.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 40.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 41.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 41.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 42.224f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 43.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 43.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 43.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 45.224f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 45.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 45.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 47.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 48.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 48.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 49.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 49.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 49.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 50.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 50.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 51.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 51.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 52.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 53.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 53.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 54.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 54.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 55.224f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 55.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 57.099f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 57.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 58.349f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 58.849f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 59.099f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 60.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 61.224f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 61.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 63.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 63.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 63.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 63.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 63.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 64.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 64.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 65.349f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 65.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 65.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 66.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 67.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 67.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 68.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 69.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 70.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 71.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 72.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.224f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 73.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 73.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 74.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 75.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 75.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 76.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 77.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 77.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 78.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 79.224f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 79.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 79.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 79.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 80.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 80.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 81.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 82.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 83.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 83.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 83.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 85.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 85.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 85.974f, 86.849f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.224f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 87.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 87.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 87.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 88.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 88.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 89.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 89.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 90.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 90.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 91.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 91.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 91.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 92.349f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 92.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 93.099f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 93.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 93.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 94.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 94.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 95.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 95.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 96.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 96.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 97.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 98.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 98.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 99.099f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 99.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 99.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 100.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 100.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 101.099f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 101.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 101.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 102.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 102.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 103.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 103.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 104.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 104.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 105.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 105.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 107.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 107.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 107.724f, 108.099f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 108.224f, 108.599f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 108.724f, 109.099f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 109.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 109.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 109.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 109.974f, 110.599f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 110.724f, 111.099f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 111.224f, 111.599f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 111.724f, 113.849f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 113.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 114.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 114.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 115.224f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 115.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 115.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 115.849f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 115.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 116.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 116.849f, 117.224f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 117.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 117.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 117.849f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 118.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 118.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 119.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 119.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 119.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 119.974f, 121.849f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 121.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 122.099f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 122.224f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 122.349f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 122.474f, 0.2f, "j"));

        }
        else if (input.Difficulty.Equals("Hard"))
        {
            input.Notes.Add(new Data.NoteInfo(false, 0.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 1.224f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 1.349f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 1.474f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 1.724f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(true, 1.974f, 3.349f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 2.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 3.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 3.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 3.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 3.974f, 5.349f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 4.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 5.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 5.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 5.599f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 5.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 5.849f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 5.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 6.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 6.599f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 6.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 6.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 7.224f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 7.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 7.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 7.974f, 8.849f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 8.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 9.474f, 9.849f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 9.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 9.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 10.099f, 10.849f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 10.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 11.224f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 11.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 11.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 11.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 11.974f, 13.099f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 12.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 13.224f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 13.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 13.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 13.599f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 13.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 13.849f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 13.974f, 14.599f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 14.724f, 15.099f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 14.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 15.224f, 15.599f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 15.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(true, 15.974f, 17.849f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 16.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 17.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 17.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 17.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 17.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 18.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 18.349f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 18.724f, 19.349f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 18.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 18.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 19.224f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 19.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 19.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 19.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 19.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 19.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 20.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 20.349f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 20.724f, 21.349f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 20.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 20.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 21.224f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 21.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 21.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 21.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 21.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 21.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 22.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 22.349f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 22.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 22.724f, 23.349f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 22.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 22.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 23.224f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 23.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(true, 23.474f, 24.349f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 23.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 23.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 23.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 24.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 24.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 24.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 24.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 25.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 25.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 25.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 25.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 25.974f, 27.224f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 26.349f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 26.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 27.224f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 27.474f, 27.849f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 27.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 27.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 27.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 27.974f, 29.224f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 28.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 28.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 28.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 29.099f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.224f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 29.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 29.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 29.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 29.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 29.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 29.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 29.974f, 30.849f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 30.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 30.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 30.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 30.974f, 31.599f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 31.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 31.224f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 31.474f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 31.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 31.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 31.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 31.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 31.974f, 33.724f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 32.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 32.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 32.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 32.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 33.099f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 33.224f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 33.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 33.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 33.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 33.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 34.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 34.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 34.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 34.599f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 34.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 34.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 34.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 35.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 35.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 35.474f, 0.2f,"q"));
            input.Notes.Add(new Data.NoteInfo(false, 35.474f, 0.2f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 35.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 36.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 36.599f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 36.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 36.849f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 36.849f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 36.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 37.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 37.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 37.849f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 37.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 38.349f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 38.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 38.599f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 38.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 38.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 38.849f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 38.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 39.224f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 39.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 39.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 39.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 39.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 40.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 40.599f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 40.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 40.849f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 40.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 40.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 41.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 41.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 41.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 42.224f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 42.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 42.599f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 42.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 42.849f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 42.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 42.974f, 0.2f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 43.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 43.474f, 0.2f, "p"));
            input.Notes.Add(new Data.NoteInfo(false, 43.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 43.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 44.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 44.599f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 44.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 44.849f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 44.974f, 0.2f,"a"));
            input.Notes.Add(new Data.NoteInfo(false, 45.224f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 45.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 45.474f, 0.2f,"q"));
            input.Notes.Add(new Data.NoteInfo(false, 45.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 45.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 46.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 46.599f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 46.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 46.849f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 46.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 47.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 47.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 48.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 48.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 48.599f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 48.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 48.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 48.849f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 48.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 49.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 49.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 49.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 49.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 49.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 49.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 49.974f, 50.599f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 50.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 50.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 50.724f, 51.099f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 50.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 50.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 51.224f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 51.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 51.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 51.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 51.724f, 52.474f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 51.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 51.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 52.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 52.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 52.724f, 53.474f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 52.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 53.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 53.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 53.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 53.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 53.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 53.974f, 54.349f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 54.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 54.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 54.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 54.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 54.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 54.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 55.224f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 55.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 55.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 55.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 55.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 55.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 55.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 56.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 56.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 56.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 56.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 56.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 56.849f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 56.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 57.099f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 57.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 57.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 57.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 57.974f, 58.599f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 58.349f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 58.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 58.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 58.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 58.849f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 58.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 59.099f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 59.224f, 60.849f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 59.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 59.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 60.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 60.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 60.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 61.224f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 61.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 61.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 61.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 61.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 61.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 62.224f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 62.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 62.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 62.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 62.849f, 63.099f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 62.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 63.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 63.224f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 63.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 63.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 63.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 63.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 63.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 63.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 63.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 63.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 63.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 64.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 64.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 64.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 64.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 64.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 64.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 64.974f, 65.349f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 65.349f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 65.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 65.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 65.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 65.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 65.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 65.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 65.974f, 67.349f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 66.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 66.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 67.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 67.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 67.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(true, 67.724f, 69.349f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 67.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 68.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 68.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 69.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 69.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(true, 69.474f, 69.849f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 69.974f, 70.349f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 69.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 70.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 70.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 70.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(true, 71.224f, 71.599f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 71.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 71.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 71.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 71.974f, 72.349f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 72.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(true, 72.724f, 73.349f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 72.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 73.224f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 73.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 73.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 73.474f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 73.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 73.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(true, 73.974f, 75.099f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 74.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 74.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 74.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 75.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 75.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 75.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 75.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 75.724f, 76.599f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 76.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 76.724f, 77.599f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 76.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 77.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 77.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 77.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 77.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 77.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 77.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 78.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 78.974f, 0.2f, "z"));
            input.Notes.Add(new Data.NoteInfo(false, 79.224f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 79.224f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 79.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 79.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 79.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 79.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 79.724f, 80.724f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 79.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 80.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 80.474f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 80.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 80.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 81.474f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 81.724f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 81.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 81.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 82.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 82.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 82.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 82.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 83.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 83.349f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 83.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 83.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 83.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 83.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 83.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 84.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 84.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 84.474f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 84.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 85.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 85.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 85.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 85.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 85.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 85.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 85.974f, 86.849f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 87.224f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 87.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 87.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 87.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 88.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 88.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 89.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 89.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 89.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 89.974f, 90.349f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 90.349f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 90.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 90.474f, 90.849f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 90.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 90.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 91.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 91.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 91.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 91.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 91.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92.349f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 92.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 92.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 92.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 93.099f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 93.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 93.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 93.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 93.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 93.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 94.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 94.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 94.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 94.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 94.849f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 94.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 94.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 95.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 95.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 95.474f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 95.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 95.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 95.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 95.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 96.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 96.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 96.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 96.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 96.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 96.849f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 96.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 96.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 97.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 97.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 97.474f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 97.474f, 97.849f, ";"));
            input.Notes.Add(new Data.NoteInfo(false, 97.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 97.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 97.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(true, 97.974f, 98.349f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 97.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 98.349f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 98.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 98.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 98.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 98.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 98.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.099f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 99.474f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 99.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 99.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 99.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 99.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 99.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.349f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 100.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 100.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 100.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 100.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 101.099f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 101.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 101.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 101.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 101.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 101.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 102.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 102.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 102.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 102.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 102.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 102.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 102.849f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 102.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 102.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 103.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 103.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 103.474f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 103.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 103.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 103.974f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 103.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 104.099f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 104.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 104.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 104.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 104.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 104.724f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 104.849f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 104.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 104.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 105.224f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 105.474f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 105.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 105.724f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 105.974f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 105.974f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 106.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 107.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 107.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 107.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(true, 107.724f, 108.099f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 108.224f, 108.599f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 108.724f, 109.099f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 108.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 109.224f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 109.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 109.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 109.724f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(true, 109.974f, 110.599f, "d"));
            input.Notes.Add(new Data.NoteInfo(true, 110.724f, 111.099f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 110.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(true, 111.224f, 111.599f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 111.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(true, 111.724f, 113.849f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 112.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 113.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 113.974f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 114.474f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 114.724f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 114.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 115.224f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 115.474f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 115.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 115.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 115.849f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 115.974f, 116.599f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 116.724f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(true, 116.849f, 117.224f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 116.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 117.474f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 117.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 117.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 117.849f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 117.974f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 118.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 118.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 118.974f, 0.2f,";"));
            input.Notes.Add(new Data.NoteInfo(false, 119.224f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 119.474f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 119.474f, 0.2f,"p"));
            input.Notes.Add(new Data.NoteInfo(false, 119.724f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(true, 119.974f, 121.849f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 120.974f, 0.2f, "a"));
            input.Notes.Add(new Data.NoteInfo(false, 121.474f, 0.2f, "q"));
            input.Notes.Add(new Data.NoteInfo(false, 121.974f, 0.2f, "s"));
            input.Notes.Add(new Data.NoteInfo(false, 121.974f, 0.2f, "l"));
            input.Notes.Add(new Data.NoteInfo(false, 122.099f, 0.2f, "d"));
            input.Notes.Add(new Data.NoteInfo(false, 122.099f, 0.2f, "k"));
            input.Notes.Add(new Data.NoteInfo(false, 122.224f, 0.2f, "f"));
            input.Notes.Add(new Data.NoteInfo(false, 122.224f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 122.349f, 0.2f, "space"));
            input.Notes.Add(new Data.NoteInfo(false, 122.474f, 0.2f, "j"));
            input.Notes.Add(new Data.NoteInfo(false, 122.474f, 0.2f, "f"));

        }
        else if (input.Difficulty.Equals("Extreme"))
        {
            input.Notes.Add(new Data.NoteInfo(true, 0.00f, 0.65f, "k"));

        }
    }
}
